//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSourceFieldsAttributesInitParameters) DeepCopyInto(out *AlertSourceFieldsAttributesInitParameters) {
	*out = *in
	if in.AlertFieldID != nil {
		in, out := &in.AlertFieldID, &out.AlertFieldID
		*out = new(string)
		**out = **in
	}
	if in.TemplateBody != nil {
		in, out := &in.TemplateBody, &out.TemplateBody
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSourceFieldsAttributesInitParameters.
func (in *AlertSourceFieldsAttributesInitParameters) DeepCopy() *AlertSourceFieldsAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(AlertSourceFieldsAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSourceFieldsAttributesObservation) DeepCopyInto(out *AlertSourceFieldsAttributesObservation) {
	*out = *in
	if in.AlertFieldID != nil {
		in, out := &in.AlertFieldID, &out.AlertFieldID
		*out = new(string)
		**out = **in
	}
	if in.TemplateBody != nil {
		in, out := &in.TemplateBody, &out.TemplateBody
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSourceFieldsAttributesObservation.
func (in *AlertSourceFieldsAttributesObservation) DeepCopy() *AlertSourceFieldsAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(AlertSourceFieldsAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSourceFieldsAttributesParameters) DeepCopyInto(out *AlertSourceFieldsAttributesParameters) {
	*out = *in
	if in.AlertFieldID != nil {
		in, out := &in.AlertFieldID, &out.AlertFieldID
		*out = new(string)
		**out = **in
	}
	if in.TemplateBody != nil {
		in, out := &in.TemplateBody, &out.TemplateBody
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSourceFieldsAttributesParameters.
func (in *AlertSourceFieldsAttributesParameters) DeepCopy() *AlertSourceFieldsAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(AlertSourceFieldsAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSourceUrgencyRulesAttributesInitParameters) DeepCopyInto(out *AlertSourceUrgencyRulesAttributesInitParameters) {
	*out = *in
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableID != nil {
		in, out := &in.ConditionableID, &out.ConditionableID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableType != nil {
		in, out := &in.ConditionableType, &out.ConditionableType
		*out = new(string)
		**out = **in
	}
	if in.JSONPath != nil {
		in, out := &in.JSONPath, &out.JSONPath
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSourceUrgencyRulesAttributesInitParameters.
func (in *AlertSourceUrgencyRulesAttributesInitParameters) DeepCopy() *AlertSourceUrgencyRulesAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(AlertSourceUrgencyRulesAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSourceUrgencyRulesAttributesObservation) DeepCopyInto(out *AlertSourceUrgencyRulesAttributesObservation) {
	*out = *in
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableID != nil {
		in, out := &in.ConditionableID, &out.ConditionableID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableType != nil {
		in, out := &in.ConditionableType, &out.ConditionableType
		*out = new(string)
		**out = **in
	}
	if in.JSONPath != nil {
		in, out := &in.JSONPath, &out.JSONPath
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSourceUrgencyRulesAttributesObservation.
func (in *AlertSourceUrgencyRulesAttributesObservation) DeepCopy() *AlertSourceUrgencyRulesAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(AlertSourceUrgencyRulesAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSourceUrgencyRulesAttributesParameters) DeepCopyInto(out *AlertSourceUrgencyRulesAttributesParameters) {
	*out = *in
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableID != nil {
		in, out := &in.ConditionableID, &out.ConditionableID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableType != nil {
		in, out := &in.ConditionableType, &out.ConditionableType
		*out = new(string)
		**out = **in
	}
	if in.JSONPath != nil {
		in, out := &in.JSONPath, &out.JSONPath
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSourceUrgencyRulesAttributesParameters.
func (in *AlertSourceUrgencyRulesAttributesParameters) DeepCopy() *AlertSourceUrgencyRulesAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(AlertSourceUrgencyRulesAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertTemplateAttributesInitParameters) DeepCopyInto(out *AlertTemplateAttributesInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalURL != nil {
		in, out := &in.ExternalURL, &out.ExternalURL
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertTemplateAttributesInitParameters.
func (in *AlertTemplateAttributesInitParameters) DeepCopy() *AlertTemplateAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(AlertTemplateAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertTemplateAttributesObservation) DeepCopyInto(out *AlertTemplateAttributesObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalURL != nil {
		in, out := &in.ExternalURL, &out.ExternalURL
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertTemplateAttributesObservation.
func (in *AlertTemplateAttributesObservation) DeepCopy() *AlertTemplateAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(AlertTemplateAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertTemplateAttributesParameters) DeepCopyInto(out *AlertTemplateAttributesParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalURL != nil {
		in, out := &in.ExternalURL, &out.ExternalURL
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertTemplateAttributesParameters.
func (in *AlertTemplateAttributesParameters) DeepCopy() *AlertTemplateAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(AlertTemplateAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSource) DeepCopyInto(out *AlertsSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSource.
func (in *AlertsSource) DeepCopy() *AlertsSource {
	if in == nil {
		return nil
	}
	out := new(AlertsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertsSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSourceInitParameters) DeepCopyInto(out *AlertsSourceInitParameters) {
	*out = *in
	if in.AlertSourceFieldsAttributes != nil {
		in, out := &in.AlertSourceFieldsAttributes, &out.AlertSourceFieldsAttributes
		*out = make([]AlertSourceFieldsAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertSourceUrgencyRulesAttributes != nil {
		in, out := &in.AlertSourceUrgencyRulesAttributes, &out.AlertSourceUrgencyRulesAttributes
		*out = make([]AlertSourceUrgencyRulesAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertTemplateAttributes != nil {
		in, out := &in.AlertTemplateAttributes, &out.AlertTemplateAttributes
		*out = make([]AlertTemplateAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.DeduplicateAlertsByKey != nil {
		in, out := &in.DeduplicateAlertsByKey, &out.DeduplicateAlertsByKey
		*out = new(bool)
		**out = **in
	}
	if in.DeduplicationKeyKind != nil {
		in, out := &in.DeduplicationKeyKind, &out.DeduplicationKeyKind
		*out = new(string)
		**out = **in
	}
	if in.DeduplicationKeyPath != nil {
		in, out := &in.DeduplicationKeyPath, &out.DeduplicationKeyPath
		*out = new(string)
		**out = **in
	}
	if in.DeduplicationKeyRegexp != nil {
		in, out := &in.DeduplicationKeyRegexp, &out.DeduplicationKeyRegexp
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResolutionRuleAttributes != nil {
		in, out := &in.ResolutionRuleAttributes, &out.ResolutionRuleAttributes
		*out = make([]ResolutionRuleAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecretSecretRef != nil {
		in, out := &in.SecretSecretRef, &out.SecretSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.SourceType != nil {
		in, out := &in.SourceType, &out.SourceType
		*out = new(string)
		**out = **in
	}
	if in.SourceableAttributes != nil {
		in, out := &in.SourceableAttributes, &out.SourceableAttributes
		*out = make([]SourceableAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.WebhookEndpoint != nil {
		in, out := &in.WebhookEndpoint, &out.WebhookEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSourceInitParameters.
func (in *AlertsSourceInitParameters) DeepCopy() *AlertsSourceInitParameters {
	if in == nil {
		return nil
	}
	out := new(AlertsSourceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSourceList) DeepCopyInto(out *AlertsSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlertsSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSourceList.
func (in *AlertsSourceList) DeepCopy() *AlertsSourceList {
	if in == nil {
		return nil
	}
	out := new(AlertsSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertsSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSourceObservation) DeepCopyInto(out *AlertsSourceObservation) {
	*out = *in
	if in.AlertSourceFieldsAttributes != nil {
		in, out := &in.AlertSourceFieldsAttributes, &out.AlertSourceFieldsAttributes
		*out = make([]AlertSourceFieldsAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertSourceUrgencyRulesAttributes != nil {
		in, out := &in.AlertSourceUrgencyRulesAttributes, &out.AlertSourceUrgencyRulesAttributes
		*out = make([]AlertSourceUrgencyRulesAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertTemplateAttributes != nil {
		in, out := &in.AlertTemplateAttributes, &out.AlertTemplateAttributes
		*out = make([]AlertTemplateAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.DeduplicateAlertsByKey != nil {
		in, out := &in.DeduplicateAlertsByKey, &out.DeduplicateAlertsByKey
		*out = new(bool)
		**out = **in
	}
	if in.DeduplicationKeyKind != nil {
		in, out := &in.DeduplicationKeyKind, &out.DeduplicationKeyKind
		*out = new(string)
		**out = **in
	}
	if in.DeduplicationKeyPath != nil {
		in, out := &in.DeduplicationKeyPath, &out.DeduplicationKeyPath
		*out = new(string)
		**out = **in
	}
	if in.DeduplicationKeyRegexp != nil {
		in, out := &in.DeduplicationKeyRegexp, &out.DeduplicationKeyRegexp
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResolutionRuleAttributes != nil {
		in, out := &in.ResolutionRuleAttributes, &out.ResolutionRuleAttributes
		*out = make([]ResolutionRuleAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourceType != nil {
		in, out := &in.SourceType, &out.SourceType
		*out = new(string)
		**out = **in
	}
	if in.SourceableAttributes != nil {
		in, out := &in.SourceableAttributes, &out.SourceableAttributes
		*out = make([]SourceableAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.WebhookEndpoint != nil {
		in, out := &in.WebhookEndpoint, &out.WebhookEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSourceObservation.
func (in *AlertsSourceObservation) DeepCopy() *AlertsSourceObservation {
	if in == nil {
		return nil
	}
	out := new(AlertsSourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSourceParameters) DeepCopyInto(out *AlertsSourceParameters) {
	*out = *in
	if in.AlertSourceFieldsAttributes != nil {
		in, out := &in.AlertSourceFieldsAttributes, &out.AlertSourceFieldsAttributes
		*out = make([]AlertSourceFieldsAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertSourceUrgencyRulesAttributes != nil {
		in, out := &in.AlertSourceUrgencyRulesAttributes, &out.AlertSourceUrgencyRulesAttributes
		*out = make([]AlertSourceUrgencyRulesAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertTemplateAttributes != nil {
		in, out := &in.AlertTemplateAttributes, &out.AlertTemplateAttributes
		*out = make([]AlertTemplateAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.DeduplicateAlertsByKey != nil {
		in, out := &in.DeduplicateAlertsByKey, &out.DeduplicateAlertsByKey
		*out = new(bool)
		**out = **in
	}
	if in.DeduplicationKeyKind != nil {
		in, out := &in.DeduplicationKeyKind, &out.DeduplicationKeyKind
		*out = new(string)
		**out = **in
	}
	if in.DeduplicationKeyPath != nil {
		in, out := &in.DeduplicationKeyPath, &out.DeduplicationKeyPath
		*out = new(string)
		**out = **in
	}
	if in.DeduplicationKeyRegexp != nil {
		in, out := &in.DeduplicationKeyRegexp, &out.DeduplicationKeyRegexp
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResolutionRuleAttributes != nil {
		in, out := &in.ResolutionRuleAttributes, &out.ResolutionRuleAttributes
		*out = make([]ResolutionRuleAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecretSecretRef != nil {
		in, out := &in.SecretSecretRef, &out.SecretSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.SourceType != nil {
		in, out := &in.SourceType, &out.SourceType
		*out = new(string)
		**out = **in
	}
	if in.SourceableAttributes != nil {
		in, out := &in.SourceableAttributes, &out.SourceableAttributes
		*out = make([]SourceableAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.WebhookEndpoint != nil {
		in, out := &in.WebhookEndpoint, &out.WebhookEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSourceParameters.
func (in *AlertsSourceParameters) DeepCopy() *AlertsSourceParameters {
	if in == nil {
		return nil
	}
	out := new(AlertsSourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSourceSpec) DeepCopyInto(out *AlertsSourceSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSourceSpec.
func (in *AlertsSourceSpec) DeepCopy() *AlertsSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AlertsSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSourceStatus) DeepCopyInto(out *AlertsSourceStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSourceStatus.
func (in *AlertsSourceStatus) DeepCopy() *AlertsSourceStatus {
	if in == nil {
		return nil
	}
	out := new(AlertsSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsAttributesInitParameters) DeepCopyInto(out *ConditionsAttributesInitParameters) {
	*out = *in
	if in.ConditionableID != nil {
		in, out := &in.ConditionableID, &out.ConditionableID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableType != nil {
		in, out := &in.ConditionableType, &out.ConditionableType
		*out = new(string)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsAttributesInitParameters.
func (in *ConditionsAttributesInitParameters) DeepCopy() *ConditionsAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionsAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsAttributesObservation) DeepCopyInto(out *ConditionsAttributesObservation) {
	*out = *in
	if in.ConditionableID != nil {
		in, out := &in.ConditionableID, &out.ConditionableID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableType != nil {
		in, out := &in.ConditionableType, &out.ConditionableType
		*out = new(string)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsAttributesObservation.
func (in *ConditionsAttributesObservation) DeepCopy() *ConditionsAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(ConditionsAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsAttributesParameters) DeepCopyInto(out *ConditionsAttributesParameters) {
	*out = *in
	if in.ConditionableID != nil {
		in, out := &in.ConditionableID, &out.ConditionableID
		*out = new(string)
		**out = **in
	}
	if in.ConditionableType != nil {
		in, out := &in.ConditionableType, &out.ConditionableType
		*out = new(string)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsAttributesParameters.
func (in *ConditionsAttributesParameters) DeepCopy() *ConditionsAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionsAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldMappingsAttributesInitParameters) DeepCopyInto(out *FieldMappingsAttributesInitParameters) {
	*out = *in
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.JSONPath != nil {
		in, out := &in.JSONPath, &out.JSONPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldMappingsAttributesInitParameters.
func (in *FieldMappingsAttributesInitParameters) DeepCopy() *FieldMappingsAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(FieldMappingsAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldMappingsAttributesObservation) DeepCopyInto(out *FieldMappingsAttributesObservation) {
	*out = *in
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.JSONPath != nil {
		in, out := &in.JSONPath, &out.JSONPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldMappingsAttributesObservation.
func (in *FieldMappingsAttributesObservation) DeepCopy() *FieldMappingsAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(FieldMappingsAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldMappingsAttributesParameters) DeepCopyInto(out *FieldMappingsAttributesParameters) {
	*out = *in
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.JSONPath != nil {
		in, out := &in.JSONPath, &out.JSONPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldMappingsAttributesParameters.
func (in *FieldMappingsAttributesParameters) DeepCopy() *FieldMappingsAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(FieldMappingsAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolutionRuleAttributesInitParameters) DeepCopyInto(out *ResolutionRuleAttributesInitParameters) {
	*out = *in
	if in.ConditionType != nil {
		in, out := &in.ConditionType, &out.ConditionType
		*out = new(string)
		**out = **in
	}
	if in.ConditionsAttributes != nil {
		in, out := &in.ConditionsAttributes, &out.ConditionsAttributes
		*out = make([]ConditionsAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IdentifierJSONPath != nil {
		in, out := &in.IdentifierJSONPath, &out.IdentifierJSONPath
		*out = new(string)
		**out = **in
	}
	if in.IdentifierMatchableID != nil {
		in, out := &in.IdentifierMatchableID, &out.IdentifierMatchableID
		*out = new(string)
		**out = **in
	}
	if in.IdentifierMatchableType != nil {
		in, out := &in.IdentifierMatchableType, &out.IdentifierMatchableType
		*out = new(string)
		**out = **in
	}
	if in.IdentifierReferenceKind != nil {
		in, out := &in.IdentifierReferenceKind, &out.IdentifierReferenceKind
		*out = new(string)
		**out = **in
	}
	if in.IdentifierValueRegex != nil {
		in, out := &in.IdentifierValueRegex, &out.IdentifierValueRegex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolutionRuleAttributesInitParameters.
func (in *ResolutionRuleAttributesInitParameters) DeepCopy() *ResolutionRuleAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ResolutionRuleAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolutionRuleAttributesObservation) DeepCopyInto(out *ResolutionRuleAttributesObservation) {
	*out = *in
	if in.ConditionType != nil {
		in, out := &in.ConditionType, &out.ConditionType
		*out = new(string)
		**out = **in
	}
	if in.ConditionsAttributes != nil {
		in, out := &in.ConditionsAttributes, &out.ConditionsAttributes
		*out = make([]ConditionsAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IdentifierJSONPath != nil {
		in, out := &in.IdentifierJSONPath, &out.IdentifierJSONPath
		*out = new(string)
		**out = **in
	}
	if in.IdentifierMatchableID != nil {
		in, out := &in.IdentifierMatchableID, &out.IdentifierMatchableID
		*out = new(string)
		**out = **in
	}
	if in.IdentifierMatchableType != nil {
		in, out := &in.IdentifierMatchableType, &out.IdentifierMatchableType
		*out = new(string)
		**out = **in
	}
	if in.IdentifierReferenceKind != nil {
		in, out := &in.IdentifierReferenceKind, &out.IdentifierReferenceKind
		*out = new(string)
		**out = **in
	}
	if in.IdentifierValueRegex != nil {
		in, out := &in.IdentifierValueRegex, &out.IdentifierValueRegex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolutionRuleAttributesObservation.
func (in *ResolutionRuleAttributesObservation) DeepCopy() *ResolutionRuleAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(ResolutionRuleAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolutionRuleAttributesParameters) DeepCopyInto(out *ResolutionRuleAttributesParameters) {
	*out = *in
	if in.ConditionType != nil {
		in, out := &in.ConditionType, &out.ConditionType
		*out = new(string)
		**out = **in
	}
	if in.ConditionsAttributes != nil {
		in, out := &in.ConditionsAttributes, &out.ConditionsAttributes
		*out = make([]ConditionsAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IdentifierJSONPath != nil {
		in, out := &in.IdentifierJSONPath, &out.IdentifierJSONPath
		*out = new(string)
		**out = **in
	}
	if in.IdentifierMatchableID != nil {
		in, out := &in.IdentifierMatchableID, &out.IdentifierMatchableID
		*out = new(string)
		**out = **in
	}
	if in.IdentifierMatchableType != nil {
		in, out := &in.IdentifierMatchableType, &out.IdentifierMatchableType
		*out = new(string)
		**out = **in
	}
	if in.IdentifierReferenceKind != nil {
		in, out := &in.IdentifierReferenceKind, &out.IdentifierReferenceKind
		*out = new(string)
		**out = **in
	}
	if in.IdentifierValueRegex != nil {
		in, out := &in.IdentifierValueRegex, &out.IdentifierValueRegex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolutionRuleAttributesParameters.
func (in *ResolutionRuleAttributesParameters) DeepCopy() *ResolutionRuleAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(ResolutionRuleAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceableAttributesInitParameters) DeepCopyInto(out *SourceableAttributesInitParameters) {
	*out = *in
	if in.AcceptThreadedEmails != nil {
		in, out := &in.AcceptThreadedEmails, &out.AcceptThreadedEmails
		*out = new(bool)
		**out = **in
	}
	if in.AutoResolve != nil {
		in, out := &in.AutoResolve, &out.AutoResolve
		*out = new(bool)
		**out = **in
	}
	if in.FieldMappingsAttributes != nil {
		in, out := &in.FieldMappingsAttributes, &out.FieldMappingsAttributes
		*out = make([]FieldMappingsAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolveState != nil {
		in, out := &in.ResolveState, &out.ResolveState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceableAttributesInitParameters.
func (in *SourceableAttributesInitParameters) DeepCopy() *SourceableAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceableAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceableAttributesObservation) DeepCopyInto(out *SourceableAttributesObservation) {
	*out = *in
	if in.AcceptThreadedEmails != nil {
		in, out := &in.AcceptThreadedEmails, &out.AcceptThreadedEmails
		*out = new(bool)
		**out = **in
	}
	if in.AutoResolve != nil {
		in, out := &in.AutoResolve, &out.AutoResolve
		*out = new(bool)
		**out = **in
	}
	if in.FieldMappingsAttributes != nil {
		in, out := &in.FieldMappingsAttributes, &out.FieldMappingsAttributes
		*out = make([]FieldMappingsAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolveState != nil {
		in, out := &in.ResolveState, &out.ResolveState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceableAttributesObservation.
func (in *SourceableAttributesObservation) DeepCopy() *SourceableAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(SourceableAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceableAttributesParameters) DeepCopyInto(out *SourceableAttributesParameters) {
	*out = *in
	if in.AcceptThreadedEmails != nil {
		in, out := &in.AcceptThreadedEmails, &out.AcceptThreadedEmails
		*out = new(bool)
		**out = **in
	}
	if in.AutoResolve != nil {
		in, out := &in.AutoResolve, &out.AutoResolve
		*out = new(bool)
		**out = **in
	}
	if in.FieldMappingsAttributes != nil {
		in, out := &in.FieldMappingsAttributes, &out.FieldMappingsAttributes
		*out = make([]FieldMappingsAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolveState != nil {
		in, out := &in.ResolveState, &out.ResolveState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceableAttributesParameters.
func (in *SourceableAttributesParameters) DeepCopy() *SourceableAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(SourceableAttributesParameters)
	in.DeepCopyInto(out)
	return out
}
