// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AlertSourceFieldsAttributesInitParameters struct {

	// The ID of the alert field
	AlertFieldID *string `json:"alertFieldId,omitempty" tf:"alert_field_id,omitempty"`

	// Liquid expression to extract a specific value from the alert's payload for evaluation
	TemplateBody *string `json:"templateBody,omitempty" tf:"template_body,omitempty"`
}

type AlertSourceFieldsAttributesObservation struct {

	// The ID of the alert field
	AlertFieldID *string `json:"alertFieldId,omitempty" tf:"alert_field_id,omitempty"`

	// Liquid expression to extract a specific value from the alert's payload for evaluation
	TemplateBody *string `json:"templateBody,omitempty" tf:"template_body,omitempty"`
}

type AlertSourceFieldsAttributesParameters struct {

	// The ID of the alert field
	// +kubebuilder:validation:Optional
	AlertFieldID *string `json:"alertFieldId,omitempty" tf:"alert_field_id,omitempty"`

	// Liquid expression to extract a specific value from the alert's payload for evaluation
	// +kubebuilder:validation:Optional
	TemplateBody *string `json:"templateBody,omitempty" tf:"template_body,omitempty"`
}

type AlertSourceUrgencyRulesAttributesInitParameters struct {

	// The ID of the alert urgency
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// The ID of the conditionable. If conditionable_type is AlertField, this is the ID of the alert field.
	ConditionableID *string `json:"conditionableId,omitempty" tf:"conditionable_id,omitempty"`

	// The type of the conditionable. Value must be one of `AlertField or (empty string)`.
	ConditionableType *string `json:"conditionableType,omitempty" tf:"conditionable_type,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`

	// The kind of the conditionable. Value must be one of `payload`, `alert_field`.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Comparison operator used to evaluate the extracted value against the specified condition. Value must be one of `is`, `is_not`, `contains`, `does_not_contain`.
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// Value that the extracted payload data is compared to using the specified operator to determine a match
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AlertSourceUrgencyRulesAttributesObservation struct {

	// The ID of the alert urgency
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// The ID of the conditionable. If conditionable_type is AlertField, this is the ID of the alert field.
	ConditionableID *string `json:"conditionableId,omitempty" tf:"conditionable_id,omitempty"`

	// The type of the conditionable. Value must be one of `AlertField or (empty string)`.
	ConditionableType *string `json:"conditionableType,omitempty" tf:"conditionable_type,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`

	// The kind of the conditionable. Value must be one of `payload`, `alert_field`.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Comparison operator used to evaluate the extracted value against the specified condition. Value must be one of `is`, `is_not`, `contains`, `does_not_contain`.
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// Value that the extracted payload data is compared to using the specified operator to determine a match
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AlertSourceUrgencyRulesAttributesParameters struct {

	// The ID of the alert urgency
	// +kubebuilder:validation:Optional
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// The ID of the conditionable. If conditionable_type is AlertField, this is the ID of the alert field.
	// +kubebuilder:validation:Optional
	ConditionableID *string `json:"conditionableId,omitempty" tf:"conditionable_id,omitempty"`

	// The type of the conditionable. Value must be one of `AlertField or (empty string)`.
	// +kubebuilder:validation:Optional
	ConditionableType *string `json:"conditionableType,omitempty" tf:"conditionable_type,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	// +kubebuilder:validation:Optional
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`

	// The kind of the conditionable. Value must be one of `payload`, `alert_field`.
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Comparison operator used to evaluate the extracted value against the specified condition. Value must be one of `is`, `is_not`, `contains`, `does_not_contain`.
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// Value that the extracted payload data is compared to using the specified operator to determine a match
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AlertTemplateAttributesInitParameters struct {

	// The alert description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The alert URL.
	ExternalURL *string `json:"externalUrl,omitempty" tf:"external_url,omitempty"`

	// The alert title.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type AlertTemplateAttributesObservation struct {

	// The alert description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The alert URL.
	ExternalURL *string `json:"externalUrl,omitempty" tf:"external_url,omitempty"`

	// The alert title.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type AlertTemplateAttributesParameters struct {

	// The alert description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The alert URL.
	// +kubebuilder:validation:Optional
	ExternalURL *string `json:"externalUrl,omitempty" tf:"external_url,omitempty"`

	// The alert title.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type AlertsSourceInitParameters struct {

	// List of alert fields to be added to the alert source. Note: This attribute requires the alert field feature to be enabled on your account. Contact Rootly customer support if you need assistance with this feature.
	AlertSourceFieldsAttributes []AlertSourceFieldsAttributesInitParameters `json:"alertSourceFieldsAttributes,omitempty" tf:"alert_source_fields_attributes,omitempty"`

	// List of rules that define the conditions under which the alert urgency will be set automatically based on the alert payload
	AlertSourceUrgencyRulesAttributes []AlertSourceUrgencyRulesAttributesInitParameters `json:"alertSourceUrgencyRulesAttributes,omitempty" tf:"alert_source_urgency_rules_attributes,omitempty"`

	// Note that when alert fields are enabled at the team level, alert template attributes cannot be provided. Use `alert_source_fields_attributes` instead.
	AlertTemplateAttributes []AlertTemplateAttributesInitParameters `json:"alertTemplateAttributes,omitempty" tf:"alert_template_attributes,omitempty"`

	// ID for the default alert urgency assigned to this alert source
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// Toggle alert deduplication using deduplication key. If enabled, deduplication_key_kind and deduplication_key_path are required.. Value must be one of true or false
	DeduplicateAlertsByKey *bool `json:"deduplicateAlertsByKey,omitempty" tf:"deduplicate_alerts_by_key,omitempty"`

	// Kind of deduplication key.. Value must be one of `payload`.
	DeduplicationKeyKind *string `json:"deduplicationKeyKind,omitempty" tf:"deduplication_key_kind,omitempty"`

	// Path to deduplication key. This is a JSON Path to extract the deduplication key from the request body.
	DeduplicationKeyPath *string `json:"deduplicationKeyPath,omitempty" tf:"deduplication_key_path,omitempty"`

	// Regular expression to extract key from value found at key path.
	DeduplicationKeyRegexp *string `json:"deduplicationKeyRegexp,omitempty" tf:"deduplication_key_regexp,omitempty"`

	// The email generated for email alert sources
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The name of the alert source
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of team IDs that will own the alert source
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// Provide additional attributes for email alerts source
	ResolutionRuleAttributes []ResolutionRuleAttributesInitParameters `json:"resolutionRuleAttributes,omitempty" tf:"resolution_rule_attributes,omitempty"`

	// The secret used to authenticate non-email alert sources
	SecretSecretRef *v2.LocalSecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// The alert source type. Value must be one of `email`, `app_dynamics`, `catchpoint`, `datadog`, `dynatrace`, `alertmanager`, `google_cloud`, `grafana`, `sentry`, `generic_webhook`, `cloud_watch`, `aws_sns`, `checkly`, `azure`, `new_relic`, `splunk`, `chronosphere`, `app_optics`, `bug_snag`, `honeycomb`, `monte_carlo`, `nagios`, `prtg`.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	// Provide additional attributes for generic_webhook alerts source
	SourceableAttributes []SourceableAttributesInitParameters `json:"sourceableAttributes,omitempty" tf:"sourceable_attributes,omitempty"`

	// The status of the alert source. Value must be one of `connected`, `setup_complete`, `setup_incomplete`.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The webhook URL generated for non-email alert sources
	WebhookEndpoint *string `json:"webhookEndpoint,omitempty" tf:"webhook_endpoint,omitempty"`
}

type AlertsSourceObservation struct {

	// List of alert fields to be added to the alert source. Note: This attribute requires the alert field feature to be enabled on your account. Contact Rootly customer support if you need assistance with this feature.
	AlertSourceFieldsAttributes []AlertSourceFieldsAttributesObservation `json:"alertSourceFieldsAttributes,omitempty" tf:"alert_source_fields_attributes,omitempty"`

	// List of rules that define the conditions under which the alert urgency will be set automatically based on the alert payload
	AlertSourceUrgencyRulesAttributes []AlertSourceUrgencyRulesAttributesObservation `json:"alertSourceUrgencyRulesAttributes,omitempty" tf:"alert_source_urgency_rules_attributes,omitempty"`

	// Note that when alert fields are enabled at the team level, alert template attributes cannot be provided. Use `alert_source_fields_attributes` instead.
	AlertTemplateAttributes []AlertTemplateAttributesObservation `json:"alertTemplateAttributes,omitempty" tf:"alert_template_attributes,omitempty"`

	// ID for the default alert urgency assigned to this alert source
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// Toggle alert deduplication using deduplication key. If enabled, deduplication_key_kind and deduplication_key_path are required.. Value must be one of true or false
	DeduplicateAlertsByKey *bool `json:"deduplicateAlertsByKey,omitempty" tf:"deduplicate_alerts_by_key,omitempty"`

	// Kind of deduplication key.. Value must be one of `payload`.
	DeduplicationKeyKind *string `json:"deduplicationKeyKind,omitempty" tf:"deduplication_key_kind,omitempty"`

	// Path to deduplication key. This is a JSON Path to extract the deduplication key from the request body.
	DeduplicationKeyPath *string `json:"deduplicationKeyPath,omitempty" tf:"deduplication_key_path,omitempty"`

	// Regular expression to extract key from value found at key path.
	DeduplicationKeyRegexp *string `json:"deduplicationKeyRegexp,omitempty" tf:"deduplication_key_regexp,omitempty"`

	// The email generated for email alert sources
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the alert source
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of team IDs that will own the alert source
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// Provide additional attributes for email alerts source
	ResolutionRuleAttributes []ResolutionRuleAttributesObservation `json:"resolutionRuleAttributes,omitempty" tf:"resolution_rule_attributes,omitempty"`

	// The alert source type. Value must be one of `email`, `app_dynamics`, `catchpoint`, `datadog`, `dynatrace`, `alertmanager`, `google_cloud`, `grafana`, `sentry`, `generic_webhook`, `cloud_watch`, `aws_sns`, `checkly`, `azure`, `new_relic`, `splunk`, `chronosphere`, `app_optics`, `bug_snag`, `honeycomb`, `monte_carlo`, `nagios`, `prtg`.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	// Provide additional attributes for generic_webhook alerts source
	SourceableAttributes []SourceableAttributesObservation `json:"sourceableAttributes,omitempty" tf:"sourceable_attributes,omitempty"`

	// The status of the alert source. Value must be one of `connected`, `setup_complete`, `setup_incomplete`.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The webhook URL generated for non-email alert sources
	WebhookEndpoint *string `json:"webhookEndpoint,omitempty" tf:"webhook_endpoint,omitempty"`
}

type AlertsSourceParameters struct {

	// List of alert fields to be added to the alert source. Note: This attribute requires the alert field feature to be enabled on your account. Contact Rootly customer support if you need assistance with this feature.
	// +kubebuilder:validation:Optional
	AlertSourceFieldsAttributes []AlertSourceFieldsAttributesParameters `json:"alertSourceFieldsAttributes,omitempty" tf:"alert_source_fields_attributes,omitempty"`

	// List of rules that define the conditions under which the alert urgency will be set automatically based on the alert payload
	// +kubebuilder:validation:Optional
	AlertSourceUrgencyRulesAttributes []AlertSourceUrgencyRulesAttributesParameters `json:"alertSourceUrgencyRulesAttributes,omitempty" tf:"alert_source_urgency_rules_attributes,omitempty"`

	// Note that when alert fields are enabled at the team level, alert template attributes cannot be provided. Use `alert_source_fields_attributes` instead.
	// +kubebuilder:validation:Optional
	AlertTemplateAttributes []AlertTemplateAttributesParameters `json:"alertTemplateAttributes,omitempty" tf:"alert_template_attributes,omitempty"`

	// ID for the default alert urgency assigned to this alert source
	// +kubebuilder:validation:Optional
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// Toggle alert deduplication using deduplication key. If enabled, deduplication_key_kind and deduplication_key_path are required.. Value must be one of true or false
	// +kubebuilder:validation:Optional
	DeduplicateAlertsByKey *bool `json:"deduplicateAlertsByKey,omitempty" tf:"deduplicate_alerts_by_key,omitempty"`

	// Kind of deduplication key.. Value must be one of `payload`.
	// +kubebuilder:validation:Optional
	DeduplicationKeyKind *string `json:"deduplicationKeyKind,omitempty" tf:"deduplication_key_kind,omitempty"`

	// Path to deduplication key. This is a JSON Path to extract the deduplication key from the request body.
	// +kubebuilder:validation:Optional
	DeduplicationKeyPath *string `json:"deduplicationKeyPath,omitempty" tf:"deduplication_key_path,omitempty"`

	// Regular expression to extract key from value found at key path.
	// +kubebuilder:validation:Optional
	DeduplicationKeyRegexp *string `json:"deduplicationKeyRegexp,omitempty" tf:"deduplication_key_regexp,omitempty"`

	// The email generated for email alert sources
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The name of the alert source
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of team IDs that will own the alert source
	// +kubebuilder:validation:Optional
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// Provide additional attributes for email alerts source
	// +kubebuilder:validation:Optional
	ResolutionRuleAttributes []ResolutionRuleAttributesParameters `json:"resolutionRuleAttributes,omitempty" tf:"resolution_rule_attributes,omitempty"`

	// The secret used to authenticate non-email alert sources
	// +kubebuilder:validation:Optional
	SecretSecretRef *v2.LocalSecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// The alert source type. Value must be one of `email`, `app_dynamics`, `catchpoint`, `datadog`, `dynatrace`, `alertmanager`, `google_cloud`, `grafana`, `sentry`, `generic_webhook`, `cloud_watch`, `aws_sns`, `checkly`, `azure`, `new_relic`, `splunk`, `chronosphere`, `app_optics`, `bug_snag`, `honeycomb`, `monte_carlo`, `nagios`, `prtg`.
	// +kubebuilder:validation:Optional
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	// Provide additional attributes for generic_webhook alerts source
	// +kubebuilder:validation:Optional
	SourceableAttributes []SourceableAttributesParameters `json:"sourceableAttributes,omitempty" tf:"sourceable_attributes,omitempty"`

	// The status of the alert source. Value must be one of `connected`, `setup_complete`, `setup_incomplete`.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The webhook URL generated for non-email alert sources
	// +kubebuilder:validation:Optional
	WebhookEndpoint *string `json:"webhookEndpoint,omitempty" tf:"webhook_endpoint,omitempty"`
}

type ConditionsAttributesInitParameters struct {

	// The ID of the conditionable. If conditionable_type is AlertField, this is the ID of the alert field.
	ConditionableID *string `json:"conditionableId,omitempty" tf:"conditionable_id,omitempty"`

	// The type of the conditionable. Value must be one of `AlertField or (empty string)`.
	ConditionableType *string `json:"conditionableType,omitempty" tf:"conditionable_type,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// The kind of the conditionable. Value must be one of `payload`, `alert_field`.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Comparison operator used to evaluate the extracted value against the specified condition. Value must be one of `is`, `is_not`, `contains`, `does_not_contain`, `starts_with`, `ends_with`.
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// Value that the extracted payload data is compared to using the specified operator to determine a match
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ConditionsAttributesObservation struct {

	// The ID of the conditionable. If conditionable_type is AlertField, this is the ID of the alert field.
	ConditionableID *string `json:"conditionableId,omitempty" tf:"conditionable_id,omitempty"`

	// The type of the conditionable. Value must be one of `AlertField or (empty string)`.
	ConditionableType *string `json:"conditionableType,omitempty" tf:"conditionable_type,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// The kind of the conditionable. Value must be one of `payload`, `alert_field`.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Comparison operator used to evaluate the extracted value against the specified condition. Value must be one of `is`, `is_not`, `contains`, `does_not_contain`, `starts_with`, `ends_with`.
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// Value that the extracted payload data is compared to using the specified operator to determine a match
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ConditionsAttributesParameters struct {

	// The ID of the conditionable. If conditionable_type is AlertField, this is the ID of the alert field.
	// +kubebuilder:validation:Optional
	ConditionableID *string `json:"conditionableId,omitempty" tf:"conditionable_id,omitempty"`

	// The type of the conditionable. Value must be one of `AlertField or (empty string)`.
	// +kubebuilder:validation:Optional
	ConditionableType *string `json:"conditionableType,omitempty" tf:"conditionable_type,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	// +kubebuilder:validation:Optional
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// The kind of the conditionable. Value must be one of `payload`, `alert_field`.
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// Comparison operator used to evaluate the extracted value against the specified condition. Value must be one of `is`, `is_not`, `contains`, `does_not_contain`, `starts_with`, `ends_with`.
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// Value that the extracted payload data is compared to using the specified operator to determine a match
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type FieldMappingsAttributesInitParameters struct {

	// Select the field on which the condition to be evaluated. Value must be one of `external_id`, `state`, `alert_title`, `alert_external_url`, `notification_target_type`, `notification_target_id`.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`
}

type FieldMappingsAttributesObservation struct {

	// Select the field on which the condition to be evaluated. Value must be one of `external_id`, `state`, `alert_title`, `alert_external_url`, `notification_target_type`, `notification_target_id`.
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`
}

type FieldMappingsAttributesParameters struct {

	// Select the field on which the condition to be evaluated. Value must be one of `external_id`, `state`, `alert_title`, `alert_external_url`, `notification_target_type`, `notification_target_id`.
	// +kubebuilder:validation:Optional
	Field *string `json:"field,omitempty" tf:"field,omitempty"`

	// JSON path expression to extract a specific value from the alert's payload for evaluation
	// +kubebuilder:validation:Optional
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`
}

type ResolutionRuleAttributesInitParameters struct {

	// The type of condition to evaluate to apply auto resolution rule. Value must be one of `all`, `any`.
	ConditionType *string `json:"conditionType,omitempty" tf:"condition_type,omitempty"`

	// List of conditions to evaluate for auto resolution
	ConditionsAttributes []ConditionsAttributesInitParameters `json:"conditionsAttributes,omitempty" tf:"conditions_attributes,omitempty"`

	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// JSON path expression to extract unique alert identifier used to match triggered alerts with resolving alerts
	IdentifierJSONPath *string `json:"identifierJsonPath,omitempty" tf:"identifier_json_path,omitempty"`

	// The ID of the identifier matchable. If identifier_matchable_type is AlertField, this is the ID of the alert field.
	IdentifierMatchableID *string `json:"identifierMatchableId,omitempty" tf:"identifier_matchable_id,omitempty"`

	// The type of the identifier matchable. Value must be one of `AlertField`.
	IdentifierMatchableType *string `json:"identifierMatchableType,omitempty" tf:"identifier_matchable_type,omitempty"`

	// The kind of the identifier reference. Value must be one of `payload`, `alert_field`.
	IdentifierReferenceKind *string `json:"identifierReferenceKind,omitempty" tf:"identifier_reference_kind,omitempty"`

	// Regex group to further specify the part of the string used as a unique identifier
	IdentifierValueRegex *string `json:"identifierValueRegex,omitempty" tf:"identifier_value_regex,omitempty"`
}

type ResolutionRuleAttributesObservation struct {

	// The type of condition to evaluate to apply auto resolution rule. Value must be one of `all`, `any`.
	ConditionType *string `json:"conditionType,omitempty" tf:"condition_type,omitempty"`

	// List of conditions to evaluate for auto resolution
	ConditionsAttributes []ConditionsAttributesObservation `json:"conditionsAttributes,omitempty" tf:"conditions_attributes,omitempty"`

	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// JSON path expression to extract unique alert identifier used to match triggered alerts with resolving alerts
	IdentifierJSONPath *string `json:"identifierJsonPath,omitempty" tf:"identifier_json_path,omitempty"`

	// The ID of the identifier matchable. If identifier_matchable_type is AlertField, this is the ID of the alert field.
	IdentifierMatchableID *string `json:"identifierMatchableId,omitempty" tf:"identifier_matchable_id,omitempty"`

	// The type of the identifier matchable. Value must be one of `AlertField`.
	IdentifierMatchableType *string `json:"identifierMatchableType,omitempty" tf:"identifier_matchable_type,omitempty"`

	// The kind of the identifier reference. Value must be one of `payload`, `alert_field`.
	IdentifierReferenceKind *string `json:"identifierReferenceKind,omitempty" tf:"identifier_reference_kind,omitempty"`

	// Regex group to further specify the part of the string used as a unique identifier
	IdentifierValueRegex *string `json:"identifierValueRegex,omitempty" tf:"identifier_value_regex,omitempty"`
}

type ResolutionRuleAttributesParameters struct {

	// The type of condition to evaluate to apply auto resolution rule. Value must be one of `all`, `any`.
	// +kubebuilder:validation:Optional
	ConditionType *string `json:"conditionType,omitempty" tf:"condition_type,omitempty"`

	// List of conditions to evaluate for auto resolution
	// +kubebuilder:validation:Optional
	ConditionsAttributes []ConditionsAttributesParameters `json:"conditionsAttributes,omitempty" tf:"conditions_attributes,omitempty"`

	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// JSON path expression to extract unique alert identifier used to match triggered alerts with resolving alerts
	// +kubebuilder:validation:Optional
	IdentifierJSONPath *string `json:"identifierJsonPath,omitempty" tf:"identifier_json_path,omitempty"`

	// The ID of the identifier matchable. If identifier_matchable_type is AlertField, this is the ID of the alert field.
	// +kubebuilder:validation:Optional
	IdentifierMatchableID *string `json:"identifierMatchableId,omitempty" tf:"identifier_matchable_id,omitempty"`

	// The type of the identifier matchable. Value must be one of `AlertField`.
	// +kubebuilder:validation:Optional
	IdentifierMatchableType *string `json:"identifierMatchableType,omitempty" tf:"identifier_matchable_type,omitempty"`

	// The kind of the identifier reference. Value must be one of `payload`, `alert_field`.
	// +kubebuilder:validation:Optional
	IdentifierReferenceKind *string `json:"identifierReferenceKind,omitempty" tf:"identifier_reference_kind,omitempty"`

	// Regex group to further specify the part of the string used as a unique identifier
	// +kubebuilder:validation:Optional
	IdentifierValueRegex *string `json:"identifierValueRegex,omitempty" tf:"identifier_value_regex,omitempty"`
}

type SourceableAttributesInitParameters struct {

	// Set this to false to reject threaded emails. Value must be one of true or false
	AcceptThreadedEmails *bool `json:"acceptThreadedEmails,omitempty" tf:"accept_threaded_emails,omitempty"`

	// Set this to true to auto-resolve alerts based on field_mappings_attributes conditions. Value must be one of true or false
	AutoResolve *bool `json:"autoResolve,omitempty" tf:"auto_resolve,omitempty"`

	// Specify rules to auto resolve alerts
	FieldMappingsAttributes []FieldMappingsAttributesInitParameters `json:"fieldMappingsAttributes,omitempty" tf:"field_mappings_attributes,omitempty"`

	// This value is matched with the value extracted from alerts payload using JSON path in field_mappings_attributes
	ResolveState *string `json:"resolveState,omitempty" tf:"resolve_state,omitempty"`
}

type SourceableAttributesObservation struct {

	// Set this to false to reject threaded emails. Value must be one of true or false
	AcceptThreadedEmails *bool `json:"acceptThreadedEmails,omitempty" tf:"accept_threaded_emails,omitempty"`

	// Set this to true to auto-resolve alerts based on field_mappings_attributes conditions. Value must be one of true or false
	AutoResolve *bool `json:"autoResolve,omitempty" tf:"auto_resolve,omitempty"`

	// Specify rules to auto resolve alerts
	FieldMappingsAttributes []FieldMappingsAttributesObservation `json:"fieldMappingsAttributes,omitempty" tf:"field_mappings_attributes,omitempty"`

	// This value is matched with the value extracted from alerts payload using JSON path in field_mappings_attributes
	ResolveState *string `json:"resolveState,omitempty" tf:"resolve_state,omitempty"`
}

type SourceableAttributesParameters struct {

	// Set this to false to reject threaded emails. Value must be one of true or false
	// +kubebuilder:validation:Optional
	AcceptThreadedEmails *bool `json:"acceptThreadedEmails,omitempty" tf:"accept_threaded_emails,omitempty"`

	// Set this to true to auto-resolve alerts based on field_mappings_attributes conditions. Value must be one of true or false
	// +kubebuilder:validation:Optional
	AutoResolve *bool `json:"autoResolve,omitempty" tf:"auto_resolve,omitempty"`

	// Specify rules to auto resolve alerts
	// +kubebuilder:validation:Optional
	FieldMappingsAttributes []FieldMappingsAttributesParameters `json:"fieldMappingsAttributes,omitempty" tf:"field_mappings_attributes,omitempty"`

	// This value is matched with the value extracted from alerts payload using JSON path in field_mappings_attributes
	// +kubebuilder:validation:Optional
	ResolveState *string `json:"resolveState,omitempty" tf:"resolve_state,omitempty"`
}

// AlertsSourceSpec defines the desired state of AlertsSource
type AlertsSourceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AlertsSourceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AlertsSourceInitParameters `json:"initProvider,omitempty"`
}

// AlertsSourceStatus defines the observed state of AlertsSource.
type AlertsSourceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AlertsSourceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AlertsSource is the Schema for the AlertsSources API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rootly}
type AlertsSource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AlertsSourceSpec   `json:"spec"`
	Status AlertsSourceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AlertsSourceList contains a list of AlertsSources
type AlertsSourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AlertsSource `json:"items"`
}

// Repository type metadata.
var (
	AlertsSource_Kind             = "AlertsSource"
	AlertsSource_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AlertsSource_Kind}.String()
	AlertsSource_KindAPIVersion   = AlertsSource_Kind + "." + CRDGroupVersion.String()
	AlertsSource_GroupVersionKind = CRDGroupVersion.WithKind(AlertsSource_Kind)
)

func init() {
	SchemeBuilder.Register(&AlertsSource{}, &AlertsSourceList{})
}
