// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AlertBroadcastChannelInitParameters struct {

	// Slack channel ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AlertBroadcastChannelObservation struct {

	// Slack channel ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AlertBroadcastChannelParameters struct {

	// Slack channel ID
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IncidentBroadcastChannelInitParameters struct {

	// Slack channel ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IncidentBroadcastChannelObservation struct {

	// Slack channel ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IncidentBroadcastChannelParameters struct {

	// Slack channel ID
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PropertiesInitParameters struct {

	// Catalog property ID
	CatalogPropertyID *string `json:"catalogPropertyId,omitempty" tf:"catalog_property_id,omitempty"`

	// The property value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type PropertiesObservation struct {

	// Catalog property ID
	CatalogPropertyID *string `json:"catalogPropertyId,omitempty" tf:"catalog_property_id,omitempty"`

	// The property value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type PropertiesParameters struct {

	// Catalog property ID
	// +kubebuilder:validation:Optional
	CatalogPropertyID *string `json:"catalogPropertyId,omitempty" tf:"catalog_property_id,omitempty"`

	// The property value
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type SlackAliasesInitParameters struct {

	// Slack alias ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack alias name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SlackAliasesObservation struct {

	// Slack alias ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack alias name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SlackAliasesParameters struct {

	// Slack alias ID
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack alias name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SlackChannelsInitParameters struct {

	// Slack channel ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SlackChannelsObservation struct {

	// Slack channel ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SlackChannelsParameters struct {

	// Slack channel ID
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Slack channel name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TeamInitParameters struct {

	// The user ids of the admins of this team. These users must also be present in user_ids attribute.
	AdminIds []*float64 `json:"adminIds,omitempty" tf:"admin_ids,omitempty"`

	// Map must contain two fields, `id` and `name`. Slack channel to broadcast alerts to
	AlertBroadcastChannel []AlertBroadcastChannelInitParameters `json:"alertBroadcastChannel,omitempty" tf:"alert_broadcast_channel,omitempty"`

	// Enable alerts to be broadcasted to a specific channel. Value must be one of true or false
	AlertBroadcastEnabled *bool `json:"alertBroadcastEnabled,omitempty" tf:"alert_broadcast_enabled,omitempty"`

	// The alert urgency id of the team
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// Auto add members to incident channel when team is attached. Value must be one of true or false
	AutoAddMembersWhenAttached *bool `json:"autoAddMembersWhenAttached,omitempty" tf:"auto_add_members_when_attached,omitempty"`

	// The Backstage entity id associated to this team. eg: :namespace/:kind/:entity_name
	BackstageID *string `json:"backstageId,omitempty" tf:"backstage_id,omitempty"`

	// The hex color of the team
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// The Cortex group id associated to this team
	CortexID *string `json:"cortexId,omitempty" tf:"cortex_id,omitempty"`

	// The description of the team
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The external id associated to this team
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// Map must contain two fields, `id` and `name`. Slack channel to broadcast incidents to
	IncidentBroadcastChannel []IncidentBroadcastChannelInitParameters `json:"incidentBroadcastChannel,omitempty" tf:"incident_broadcast_channel,omitempty"`

	// Enable incidents to be broadcasted to a specific channel. Value must be one of true or false
	IncidentBroadcastEnabled *bool `json:"incidentBroadcastEnabled,omitempty" tf:"incident_broadcast_enabled,omitempty"`

	// The name of the team
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Emails to attach to the team
	NotifyEmails []*string `json:"notifyEmails,omitempty" tf:"notify_emails,omitempty"`

	// The Opsgenie group id associated to this team
	OpsgenieID *string `json:"opsgenieId,omitempty" tf:"opsgenie_id,omitempty"`

	// The PagerDuty group id associated to this team
	PagerdutyID *string `json:"pagerdutyId,omitempty" tf:"pagerduty_id,omitempty"`

	// The PagerDuty service id associated to this team
	PagerdutyServiceID *string `json:"pagerdutyServiceId,omitempty" tf:"pagerduty_service_id,omitempty"`

	// The PagerTree group id associated to this team
	PagertreeID *string `json:"pagertreeId,omitempty" tf:"pagertree_id,omitempty"`

	// Position of the team
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// Array of property values for this team.
	Properties []PropertiesInitParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// The Service Now CI sys id associated to this team
	ServiceNowCiSysID *string `json:"serviceNowCiSysId,omitempty" tf:"service_now_ci_sys_id,omitempty"`

	// Slack Aliases associated with this team
	SlackAliases []SlackAliasesInitParameters `json:"slackAliases,omitempty" tf:"slack_aliases,omitempty"`

	// Slack Channels associated with this team
	SlackChannels []SlackChannelsInitParameters `json:"slackChannels,omitempty" tf:"slack_channels,omitempty"`

	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// The user ids of the members of this team.
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`

	// The VictorOps group id associated to this team
	VictorOpsID *string `json:"victorOpsId,omitempty" tf:"victor_ops_id,omitempty"`
}

type TeamObservation struct {

	// The user ids of the admins of this team. These users must also be present in user_ids attribute.
	AdminIds []*float64 `json:"adminIds,omitempty" tf:"admin_ids,omitempty"`

	// Map must contain two fields, `id` and `name`. Slack channel to broadcast alerts to
	AlertBroadcastChannel []AlertBroadcastChannelObservation `json:"alertBroadcastChannel,omitempty" tf:"alert_broadcast_channel,omitempty"`

	// Enable alerts to be broadcasted to a specific channel. Value must be one of true or false
	AlertBroadcastEnabled *bool `json:"alertBroadcastEnabled,omitempty" tf:"alert_broadcast_enabled,omitempty"`

	// The alert urgency id of the team
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// Auto add members to incident channel when team is attached. Value must be one of true or false
	AutoAddMembersWhenAttached *bool `json:"autoAddMembersWhenAttached,omitempty" tf:"auto_add_members_when_attached,omitempty"`

	// The Backstage entity id associated to this team. eg: :namespace/:kind/:entity_name
	BackstageID *string `json:"backstageId,omitempty" tf:"backstage_id,omitempty"`

	// The hex color of the team
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// The Cortex group id associated to this team
	CortexID *string `json:"cortexId,omitempty" tf:"cortex_id,omitempty"`

	// The description of the team
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The external id associated to this team
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Map must contain two fields, `id` and `name`. Slack channel to broadcast incidents to
	IncidentBroadcastChannel []IncidentBroadcastChannelObservation `json:"incidentBroadcastChannel,omitempty" tf:"incident_broadcast_channel,omitempty"`

	// Enable incidents to be broadcasted to a specific channel. Value must be one of true or false
	IncidentBroadcastEnabled *bool `json:"incidentBroadcastEnabled,omitempty" tf:"incident_broadcast_enabled,omitempty"`

	// The name of the team
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Emails to attach to the team
	NotifyEmails []*string `json:"notifyEmails,omitempty" tf:"notify_emails,omitempty"`

	// The Opsgenie group id associated to this team
	OpsgenieID *string `json:"opsgenieId,omitempty" tf:"opsgenie_id,omitempty"`

	// The PagerDuty group id associated to this team
	PagerdutyID *string `json:"pagerdutyId,omitempty" tf:"pagerduty_id,omitempty"`

	// The PagerDuty service id associated to this team
	PagerdutyServiceID *string `json:"pagerdutyServiceId,omitempty" tf:"pagerduty_service_id,omitempty"`

	// The PagerTree group id associated to this team
	PagertreeID *string `json:"pagertreeId,omitempty" tf:"pagertree_id,omitempty"`

	// Position of the team
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// Array of property values for this team.
	Properties []PropertiesObservation `json:"properties,omitempty" tf:"properties,omitempty"`

	// The Service Now CI sys id associated to this team
	ServiceNowCiSysID *string `json:"serviceNowCiSysId,omitempty" tf:"service_now_ci_sys_id,omitempty"`

	// Slack Aliases associated with this team
	SlackAliases []SlackAliasesObservation `json:"slackAliases,omitempty" tf:"slack_aliases,omitempty"`

	// Slack Channels associated with this team
	SlackChannels []SlackChannelsObservation `json:"slackChannels,omitempty" tf:"slack_channels,omitempty"`

	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// The user ids of the members of this team.
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`

	// The VictorOps group id associated to this team
	VictorOpsID *string `json:"victorOpsId,omitempty" tf:"victor_ops_id,omitempty"`
}

type TeamParameters struct {

	// The user ids of the admins of this team. These users must also be present in user_ids attribute.
	// +kubebuilder:validation:Optional
	AdminIds []*float64 `json:"adminIds,omitempty" tf:"admin_ids,omitempty"`

	// Map must contain two fields, `id` and `name`. Slack channel to broadcast alerts to
	// +kubebuilder:validation:Optional
	AlertBroadcastChannel []AlertBroadcastChannelParameters `json:"alertBroadcastChannel,omitempty" tf:"alert_broadcast_channel,omitempty"`

	// Enable alerts to be broadcasted to a specific channel. Value must be one of true or false
	// +kubebuilder:validation:Optional
	AlertBroadcastEnabled *bool `json:"alertBroadcastEnabled,omitempty" tf:"alert_broadcast_enabled,omitempty"`

	// The alert urgency id of the team
	// +kubebuilder:validation:Optional
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// Auto add members to incident channel when team is attached. Value must be one of true or false
	// +kubebuilder:validation:Optional
	AutoAddMembersWhenAttached *bool `json:"autoAddMembersWhenAttached,omitempty" tf:"auto_add_members_when_attached,omitempty"`

	// The Backstage entity id associated to this team. eg: :namespace/:kind/:entity_name
	// +kubebuilder:validation:Optional
	BackstageID *string `json:"backstageId,omitempty" tf:"backstage_id,omitempty"`

	// The hex color of the team
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// The Cortex group id associated to this team
	// +kubebuilder:validation:Optional
	CortexID *string `json:"cortexId,omitempty" tf:"cortex_id,omitempty"`

	// The description of the team
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The external id associated to this team
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// Map must contain two fields, `id` and `name`. Slack channel to broadcast incidents to
	// +kubebuilder:validation:Optional
	IncidentBroadcastChannel []IncidentBroadcastChannelParameters `json:"incidentBroadcastChannel,omitempty" tf:"incident_broadcast_channel,omitempty"`

	// Enable incidents to be broadcasted to a specific channel. Value must be one of true or false
	// +kubebuilder:validation:Optional
	IncidentBroadcastEnabled *bool `json:"incidentBroadcastEnabled,omitempty" tf:"incident_broadcast_enabled,omitempty"`

	// The name of the team
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Emails to attach to the team
	// +kubebuilder:validation:Optional
	NotifyEmails []*string `json:"notifyEmails,omitempty" tf:"notify_emails,omitempty"`

	// The Opsgenie group id associated to this team
	// +kubebuilder:validation:Optional
	OpsgenieID *string `json:"opsgenieId,omitempty" tf:"opsgenie_id,omitempty"`

	// The PagerDuty group id associated to this team
	// +kubebuilder:validation:Optional
	PagerdutyID *string `json:"pagerdutyId,omitempty" tf:"pagerduty_id,omitempty"`

	// The PagerDuty service id associated to this team
	// +kubebuilder:validation:Optional
	PagerdutyServiceID *string `json:"pagerdutyServiceId,omitempty" tf:"pagerduty_service_id,omitempty"`

	// The PagerTree group id associated to this team
	// +kubebuilder:validation:Optional
	PagertreeID *string `json:"pagertreeId,omitempty" tf:"pagertree_id,omitempty"`

	// Position of the team
	// +kubebuilder:validation:Optional
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// Array of property values for this team.
	// +kubebuilder:validation:Optional
	Properties []PropertiesParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// The Service Now CI sys id associated to this team
	// +kubebuilder:validation:Optional
	ServiceNowCiSysID *string `json:"serviceNowCiSysId,omitempty" tf:"service_now_ci_sys_id,omitempty"`

	// Slack Aliases associated with this team
	// +kubebuilder:validation:Optional
	SlackAliases []SlackAliasesParameters `json:"slackAliases,omitempty" tf:"slack_aliases,omitempty"`

	// Slack Channels associated with this team
	// +kubebuilder:validation:Optional
	SlackChannels []SlackChannelsParameters `json:"slackChannels,omitempty" tf:"slack_channels,omitempty"`

	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// The user ids of the members of this team.
	// +kubebuilder:validation:Optional
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`

	// The VictorOps group id associated to this team
	// +kubebuilder:validation:Optional
	VictorOpsID *string `json:"victorOpsId,omitempty" tf:"victor_ops_id,omitempty"`
}

// TeamSpec defines the desired state of Team
type TeamSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TeamParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamInitParameters `json:"initProvider,omitempty"`
}

// TeamStatus defines the observed state of Team.
type TeamStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TeamObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Team is the Schema for the Teams API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rootly}
type Team struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TeamSpec   `json:"spec"`
	Status TeamStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamList contains a list of Teams
type TeamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Team `json:"items"`
}

// Repository type metadata.
var (
	Team_Kind             = "Team"
	Team_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Team_Kind}.String()
	Team_KindAPIVersion   = Team_Kind + "." + CRDGroupVersion.String()
	Team_GroupVersionKind = CRDGroupVersion.WithKind(Team_Kind)
)

func init() {
	SchemeBuilder.Register(&Team{}, &TeamList{})
}
