//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveTimeAttributesInitParameters) DeepCopyInto(out *ActiveTimeAttributesInitParameters) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveTimeAttributesInitParameters.
func (in *ActiveTimeAttributesInitParameters) DeepCopy() *ActiveTimeAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ActiveTimeAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveTimeAttributesObservation) DeepCopyInto(out *ActiveTimeAttributesObservation) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveTimeAttributesObservation.
func (in *ActiveTimeAttributesObservation) DeepCopy() *ActiveTimeAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(ActiveTimeAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveTimeAttributesParameters) DeepCopyInto(out *ActiveTimeAttributesParameters) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveTimeAttributesParameters.
func (in *ActiveTimeAttributesParameters) DeepCopy() *ActiveTimeAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(ActiveTimeAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Schedule) DeepCopyInto(out *Schedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schedule.
func (in *Schedule) DeepCopy() *Schedule {
	if in == nil {
		return nil
	}
	out := new(Schedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Schedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleInitParameters) DeepCopyInto(out *ScheduleInitParameters) {
	*out = *in
	if in.AllTimeCoverage != nil {
		in, out := &in.AllTimeCoverage, &out.AllTimeCoverage
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IncludeShadowsInSlackNotifications != nil {
		in, out := &in.IncludeShadowsInSlackNotifications, &out.IncludeShadowsInSlackNotifications
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OwnerUserID != nil {
		in, out := &in.OwnerUserID, &out.OwnerUserID
		*out = new(float64)
		**out = **in
	}
	if in.ShiftReportDayOfWeek != nil {
		in, out := &in.ShiftReportDayOfWeek, &out.ShiftReportDayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportEnabled != nil {
		in, out := &in.ShiftReportEnabled, &out.ShiftReportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftReportTimeOfDay != nil {
		in, out := &in.ShiftReportTimeOfDay, &out.ShiftReportTimeOfDay
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportTimeZone != nil {
		in, out := &in.ShiftReportTimeZone, &out.ShiftReportTimeZone
		*out = new(string)
		**out = **in
	}
	if in.ShiftStartNotificationsEnabled != nil {
		in, out := &in.ShiftStartNotificationsEnabled, &out.ShiftStartNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftUpdateNotificationsEnabled != nil {
		in, out := &in.ShiftUpdateNotificationsEnabled, &out.ShiftUpdateNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SlackChannel != nil {
		in, out := &in.SlackChannel, &out.SlackChannel
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SlackUserGroup != nil {
		in, out := &in.SlackUserGroup, &out.SlackUserGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SyncLinearEnabled != nil {
		in, out := &in.SyncLinearEnabled, &out.SyncLinearEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleInitParameters.
func (in *ScheduleInitParameters) DeepCopy() *ScheduleInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleList) DeepCopyInto(out *ScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Schedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleList.
func (in *ScheduleList) DeepCopy() *ScheduleList {
	if in == nil {
		return nil
	}
	out := new(ScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleObservation) DeepCopyInto(out *ScheduleObservation) {
	*out = *in
	if in.AllTimeCoverage != nil {
		in, out := &in.AllTimeCoverage, &out.AllTimeCoverage
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncludeShadowsInSlackNotifications != nil {
		in, out := &in.IncludeShadowsInSlackNotifications, &out.IncludeShadowsInSlackNotifications
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OwnerUserID != nil {
		in, out := &in.OwnerUserID, &out.OwnerUserID
		*out = new(float64)
		**out = **in
	}
	if in.ShiftReportDayOfWeek != nil {
		in, out := &in.ShiftReportDayOfWeek, &out.ShiftReportDayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportEnabled != nil {
		in, out := &in.ShiftReportEnabled, &out.ShiftReportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftReportTimeOfDay != nil {
		in, out := &in.ShiftReportTimeOfDay, &out.ShiftReportTimeOfDay
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportTimeZone != nil {
		in, out := &in.ShiftReportTimeZone, &out.ShiftReportTimeZone
		*out = new(string)
		**out = **in
	}
	if in.ShiftStartNotificationsEnabled != nil {
		in, out := &in.ShiftStartNotificationsEnabled, &out.ShiftStartNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftUpdateNotificationsEnabled != nil {
		in, out := &in.ShiftUpdateNotificationsEnabled, &out.ShiftUpdateNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SlackChannel != nil {
		in, out := &in.SlackChannel, &out.SlackChannel
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SlackUserGroup != nil {
		in, out := &in.SlackUserGroup, &out.SlackUserGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SyncLinearEnabled != nil {
		in, out := &in.SyncLinearEnabled, &out.SyncLinearEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleObservation.
func (in *ScheduleObservation) DeepCopy() *ScheduleObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleParameters) DeepCopyInto(out *ScheduleParameters) {
	*out = *in
	if in.AllTimeCoverage != nil {
		in, out := &in.AllTimeCoverage, &out.AllTimeCoverage
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IncludeShadowsInSlackNotifications != nil {
		in, out := &in.IncludeShadowsInSlackNotifications, &out.IncludeShadowsInSlackNotifications
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OwnerUserID != nil {
		in, out := &in.OwnerUserID, &out.OwnerUserID
		*out = new(float64)
		**out = **in
	}
	if in.ShiftReportDayOfWeek != nil {
		in, out := &in.ShiftReportDayOfWeek, &out.ShiftReportDayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportEnabled != nil {
		in, out := &in.ShiftReportEnabled, &out.ShiftReportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftReportTimeOfDay != nil {
		in, out := &in.ShiftReportTimeOfDay, &out.ShiftReportTimeOfDay
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportTimeZone != nil {
		in, out := &in.ShiftReportTimeZone, &out.ShiftReportTimeZone
		*out = new(string)
		**out = **in
	}
	if in.ShiftStartNotificationsEnabled != nil {
		in, out := &in.ShiftStartNotificationsEnabled, &out.ShiftStartNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftUpdateNotificationsEnabled != nil {
		in, out := &in.ShiftUpdateNotificationsEnabled, &out.ShiftUpdateNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SlackChannel != nil {
		in, out := &in.SlackChannel, &out.SlackChannel
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SlackUserGroup != nil {
		in, out := &in.SlackUserGroup, &out.SlackUserGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SyncLinearEnabled != nil {
		in, out := &in.SyncLinearEnabled, &out.SyncLinearEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleParameters.
func (in *ScheduleParameters) DeepCopy() *ScheduleParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotation) DeepCopyInto(out *ScheduleRotation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotation.
func (in *ScheduleRotation) DeepCopy() *ScheduleRotation {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduleRotation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationInitParameters) DeepCopyInto(out *ScheduleRotationInitParameters) {
	*out = *in
	if in.ActiveAllWeek != nil {
		in, out := &in.ActiveAllWeek, &out.ActiveAllWeek
		*out = new(bool)
		**out = **in
	}
	if in.ActiveDays != nil {
		in, out := &in.ActiveDays, &out.ActiveDays
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ActiveTimeAttributes != nil {
		in, out := &in.ActiveTimeAttributes, &out.ActiveTimeAttributes
		*out = make([]ActiveTimeAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveTimeType != nil {
		in, out := &in.ActiveTimeType, &out.ActiveTimeType
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.ScheduleID != nil {
		in, out := &in.ScheduleID, &out.ScheduleID
		*out = new(string)
		**out = **in
	}
	if in.ScheduleIDRef != nil {
		in, out := &in.ScheduleIDRef, &out.ScheduleIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleIDSelector != nil {
		in, out := &in.ScheduleIDSelector, &out.ScheduleIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRotationMembers != nil {
		in, out := &in.ScheduleRotationMembers, &out.ScheduleRotationMembers
		*out = make([]ScheduleRotationMembersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScheduleRotationableAttributes != nil {
		in, out := &in.ScheduleRotationableAttributes, &out.ScheduleRotationableAttributes
		*out = new(ScheduleRotationableAttributesInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRotationableType != nil {
		in, out := &in.ScheduleRotationableType, &out.ScheduleRotationableType
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationInitParameters.
func (in *ScheduleRotationInitParameters) DeepCopy() *ScheduleRotationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationList) DeepCopyInto(out *ScheduleRotationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScheduleRotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationList.
func (in *ScheduleRotationList) DeepCopy() *ScheduleRotationList {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduleRotationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationMembersInitParameters) DeepCopyInto(out *ScheduleRotationMembersInitParameters) {
	*out = *in
	if in.MemberID != nil {
		in, out := &in.MemberID, &out.MemberID
		*out = new(string)
		**out = **in
	}
	if in.MemberType != nil {
		in, out := &in.MemberType, &out.MemberType
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationMembersInitParameters.
func (in *ScheduleRotationMembersInitParameters) DeepCopy() *ScheduleRotationMembersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationMembersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationMembersObservation) DeepCopyInto(out *ScheduleRotationMembersObservation) {
	*out = *in
	if in.MemberID != nil {
		in, out := &in.MemberID, &out.MemberID
		*out = new(string)
		**out = **in
	}
	if in.MemberType != nil {
		in, out := &in.MemberType, &out.MemberType
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationMembersObservation.
func (in *ScheduleRotationMembersObservation) DeepCopy() *ScheduleRotationMembersObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationMembersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationMembersParameters) DeepCopyInto(out *ScheduleRotationMembersParameters) {
	*out = *in
	if in.MemberID != nil {
		in, out := &in.MemberID, &out.MemberID
		*out = new(string)
		**out = **in
	}
	if in.MemberType != nil {
		in, out := &in.MemberType, &out.MemberType
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationMembersParameters.
func (in *ScheduleRotationMembersParameters) DeepCopy() *ScheduleRotationMembersParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationMembersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationObservation) DeepCopyInto(out *ScheduleRotationObservation) {
	*out = *in
	if in.ActiveAllWeek != nil {
		in, out := &in.ActiveAllWeek, &out.ActiveAllWeek
		*out = new(bool)
		**out = **in
	}
	if in.ActiveDays != nil {
		in, out := &in.ActiveDays, &out.ActiveDays
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ActiveTimeAttributes != nil {
		in, out := &in.ActiveTimeAttributes, &out.ActiveTimeAttributes
		*out = make([]ActiveTimeAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveTimeType != nil {
		in, out := &in.ActiveTimeType, &out.ActiveTimeType
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.ScheduleID != nil {
		in, out := &in.ScheduleID, &out.ScheduleID
		*out = new(string)
		**out = **in
	}
	if in.ScheduleRotationMembers != nil {
		in, out := &in.ScheduleRotationMembers, &out.ScheduleRotationMembers
		*out = make([]ScheduleRotationMembersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScheduleRotationableAttributes != nil {
		in, out := &in.ScheduleRotationableAttributes, &out.ScheduleRotationableAttributes
		*out = new(ScheduleRotationableAttributesObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRotationableType != nil {
		in, out := &in.ScheduleRotationableType, &out.ScheduleRotationableType
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationObservation.
func (in *ScheduleRotationObservation) DeepCopy() *ScheduleRotationObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationParameters) DeepCopyInto(out *ScheduleRotationParameters) {
	*out = *in
	if in.ActiveAllWeek != nil {
		in, out := &in.ActiveAllWeek, &out.ActiveAllWeek
		*out = new(bool)
		**out = **in
	}
	if in.ActiveDays != nil {
		in, out := &in.ActiveDays, &out.ActiveDays
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ActiveTimeAttributes != nil {
		in, out := &in.ActiveTimeAttributes, &out.ActiveTimeAttributes
		*out = make([]ActiveTimeAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveTimeType != nil {
		in, out := &in.ActiveTimeType, &out.ActiveTimeType
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.ScheduleID != nil {
		in, out := &in.ScheduleID, &out.ScheduleID
		*out = new(string)
		**out = **in
	}
	if in.ScheduleIDRef != nil {
		in, out := &in.ScheduleIDRef, &out.ScheduleIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleIDSelector != nil {
		in, out := &in.ScheduleIDSelector, &out.ScheduleIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRotationMembers != nil {
		in, out := &in.ScheduleRotationMembers, &out.ScheduleRotationMembers
		*out = make([]ScheduleRotationMembersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScheduleRotationableAttributes != nil {
		in, out := &in.ScheduleRotationableAttributes, &out.ScheduleRotationableAttributes
		*out = new(ScheduleRotationableAttributesParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRotationableType != nil {
		in, out := &in.ScheduleRotationableType, &out.ScheduleRotationableType
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationParameters.
func (in *ScheduleRotationParameters) DeepCopy() *ScheduleRotationParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationSpec) DeepCopyInto(out *ScheduleRotationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationSpec.
func (in *ScheduleRotationSpec) DeepCopy() *ScheduleRotationSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationStatus) DeepCopyInto(out *ScheduleRotationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationStatus.
func (in *ScheduleRotationStatus) DeepCopy() *ScheduleRotationStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationUser) DeepCopyInto(out *ScheduleRotationUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationUser.
func (in *ScheduleRotationUser) DeepCopy() *ScheduleRotationUser {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduleRotationUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationUserInitParameters) DeepCopyInto(out *ScheduleRotationUserInitParameters) {
	*out = *in
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.ScheduleRotationID != nil {
		in, out := &in.ScheduleRotationID, &out.ScheduleRotationID
		*out = new(string)
		**out = **in
	}
	if in.ScheduleRotationIDRef != nil {
		in, out := &in.ScheduleRotationIDRef, &out.ScheduleRotationIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRotationIDSelector != nil {
		in, out := &in.ScheduleRotationIDSelector, &out.ScheduleRotationIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationUserInitParameters.
func (in *ScheduleRotationUserInitParameters) DeepCopy() *ScheduleRotationUserInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationUserInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationUserList) DeepCopyInto(out *ScheduleRotationUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScheduleRotationUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationUserList.
func (in *ScheduleRotationUserList) DeepCopy() *ScheduleRotationUserList {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduleRotationUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationUserObservation) DeepCopyInto(out *ScheduleRotationUserObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.ScheduleRotationID != nil {
		in, out := &in.ScheduleRotationID, &out.ScheduleRotationID
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationUserObservation.
func (in *ScheduleRotationUserObservation) DeepCopy() *ScheduleRotationUserObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationUserObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationUserParameters) DeepCopyInto(out *ScheduleRotationUserParameters) {
	*out = *in
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.ScheduleRotationID != nil {
		in, out := &in.ScheduleRotationID, &out.ScheduleRotationID
		*out = new(string)
		**out = **in
	}
	if in.ScheduleRotationIDRef != nil {
		in, out := &in.ScheduleRotationIDRef, &out.ScheduleRotationIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRotationIDSelector != nil {
		in, out := &in.ScheduleRotationIDSelector, &out.ScheduleRotationIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationUserParameters.
func (in *ScheduleRotationUserParameters) DeepCopy() *ScheduleRotationUserParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationUserParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationUserSpec) DeepCopyInto(out *ScheduleRotationUserSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationUserSpec.
func (in *ScheduleRotationUserSpec) DeepCopy() *ScheduleRotationUserSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationUserStatus) DeepCopyInto(out *ScheduleRotationUserStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationUserStatus.
func (in *ScheduleRotationUserStatus) DeepCopy() *ScheduleRotationUserStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationableAttributesInitParameters) DeepCopyInto(out *ScheduleRotationableAttributesInitParameters) {
	*out = *in
	if in.HandoffDay != nil {
		in, out := &in.HandoffDay, &out.HandoffDay
		*out = new(string)
		**out = **in
	}
	if in.HandoffTime != nil {
		in, out := &in.HandoffTime, &out.HandoffTime
		*out = new(string)
		**out = **in
	}
	if in.ShiftLength != nil {
		in, out := &in.ShiftLength, &out.ShiftLength
		*out = new(float64)
		**out = **in
	}
	if in.ShiftLengthUnit != nil {
		in, out := &in.ShiftLengthUnit, &out.ShiftLengthUnit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationableAttributesInitParameters.
func (in *ScheduleRotationableAttributesInitParameters) DeepCopy() *ScheduleRotationableAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationableAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationableAttributesObservation) DeepCopyInto(out *ScheduleRotationableAttributesObservation) {
	*out = *in
	if in.HandoffDay != nil {
		in, out := &in.HandoffDay, &out.HandoffDay
		*out = new(string)
		**out = **in
	}
	if in.HandoffTime != nil {
		in, out := &in.HandoffTime, &out.HandoffTime
		*out = new(string)
		**out = **in
	}
	if in.ShiftLength != nil {
		in, out := &in.ShiftLength, &out.ShiftLength
		*out = new(float64)
		**out = **in
	}
	if in.ShiftLengthUnit != nil {
		in, out := &in.ShiftLengthUnit, &out.ShiftLengthUnit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationableAttributesObservation.
func (in *ScheduleRotationableAttributesObservation) DeepCopy() *ScheduleRotationableAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationableAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleRotationableAttributesParameters) DeepCopyInto(out *ScheduleRotationableAttributesParameters) {
	*out = *in
	if in.HandoffDay != nil {
		in, out := &in.HandoffDay, &out.HandoffDay
		*out = new(string)
		**out = **in
	}
	if in.HandoffTime != nil {
		in, out := &in.HandoffTime, &out.HandoffTime
		*out = new(string)
		**out = **in
	}
	if in.ShiftLength != nil {
		in, out := &in.ShiftLength, &out.ShiftLength
		*out = new(float64)
		**out = **in
	}
	if in.ShiftLengthUnit != nil {
		in, out := &in.ShiftLengthUnit, &out.ShiftLengthUnit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleRotationableAttributesParameters.
func (in *ScheduleRotationableAttributesParameters) DeepCopy() *ScheduleRotationableAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleRotationableAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleSpec) DeepCopyInto(out *ScheduleSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleSpec.
func (in *ScheduleSpec) DeepCopy() *ScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleStatus) DeepCopyInto(out *ScheduleStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleStatus.
func (in *ScheduleStatus) DeepCopy() *ScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduleStatus)
	in.DeepCopyInto(out)
	return out
}
