//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Schedule) DeepCopyInto(out *Schedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schedule.
func (in *Schedule) DeepCopy() *Schedule {
	if in == nil {
		return nil
	}
	out := new(Schedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Schedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleInitParameters) DeepCopyInto(out *ScheduleInitParameters) {
	*out = *in
	if in.AllTimeCoverage != nil {
		in, out := &in.AllTimeCoverage, &out.AllTimeCoverage
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IncludeShadowsInSlackNotifications != nil {
		in, out := &in.IncludeShadowsInSlackNotifications, &out.IncludeShadowsInSlackNotifications
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OwnerUserID != nil {
		in, out := &in.OwnerUserID, &out.OwnerUserID
		*out = new(float64)
		**out = **in
	}
	if in.ShiftReportDayOfWeek != nil {
		in, out := &in.ShiftReportDayOfWeek, &out.ShiftReportDayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportEnabled != nil {
		in, out := &in.ShiftReportEnabled, &out.ShiftReportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftReportTimeOfDay != nil {
		in, out := &in.ShiftReportTimeOfDay, &out.ShiftReportTimeOfDay
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportTimeZone != nil {
		in, out := &in.ShiftReportTimeZone, &out.ShiftReportTimeZone
		*out = new(string)
		**out = **in
	}
	if in.ShiftStartNotificationsEnabled != nil {
		in, out := &in.ShiftStartNotificationsEnabled, &out.ShiftStartNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftUpdateNotificationsEnabled != nil {
		in, out := &in.ShiftUpdateNotificationsEnabled, &out.ShiftUpdateNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SlackChannel != nil {
		in, out := &in.SlackChannel, &out.SlackChannel
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SlackUserGroup != nil {
		in, out := &in.SlackUserGroup, &out.SlackUserGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SyncLinearEnabled != nil {
		in, out := &in.SyncLinearEnabled, &out.SyncLinearEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleInitParameters.
func (in *ScheduleInitParameters) DeepCopy() *ScheduleInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleList) DeepCopyInto(out *ScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Schedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleList.
func (in *ScheduleList) DeepCopy() *ScheduleList {
	if in == nil {
		return nil
	}
	out := new(ScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleObservation) DeepCopyInto(out *ScheduleObservation) {
	*out = *in
	if in.AllTimeCoverage != nil {
		in, out := &in.AllTimeCoverage, &out.AllTimeCoverage
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncludeShadowsInSlackNotifications != nil {
		in, out := &in.IncludeShadowsInSlackNotifications, &out.IncludeShadowsInSlackNotifications
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OwnerUserID != nil {
		in, out := &in.OwnerUserID, &out.OwnerUserID
		*out = new(float64)
		**out = **in
	}
	if in.ShiftReportDayOfWeek != nil {
		in, out := &in.ShiftReportDayOfWeek, &out.ShiftReportDayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportEnabled != nil {
		in, out := &in.ShiftReportEnabled, &out.ShiftReportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftReportTimeOfDay != nil {
		in, out := &in.ShiftReportTimeOfDay, &out.ShiftReportTimeOfDay
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportTimeZone != nil {
		in, out := &in.ShiftReportTimeZone, &out.ShiftReportTimeZone
		*out = new(string)
		**out = **in
	}
	if in.ShiftStartNotificationsEnabled != nil {
		in, out := &in.ShiftStartNotificationsEnabled, &out.ShiftStartNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftUpdateNotificationsEnabled != nil {
		in, out := &in.ShiftUpdateNotificationsEnabled, &out.ShiftUpdateNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SlackChannel != nil {
		in, out := &in.SlackChannel, &out.SlackChannel
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SlackUserGroup != nil {
		in, out := &in.SlackUserGroup, &out.SlackUserGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SyncLinearEnabled != nil {
		in, out := &in.SyncLinearEnabled, &out.SyncLinearEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleObservation.
func (in *ScheduleObservation) DeepCopy() *ScheduleObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleParameters) DeepCopyInto(out *ScheduleParameters) {
	*out = *in
	if in.AllTimeCoverage != nil {
		in, out := &in.AllTimeCoverage, &out.AllTimeCoverage
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IncludeShadowsInSlackNotifications != nil {
		in, out := &in.IncludeShadowsInSlackNotifications, &out.IncludeShadowsInSlackNotifications
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OwnerUserID != nil {
		in, out := &in.OwnerUserID, &out.OwnerUserID
		*out = new(float64)
		**out = **in
	}
	if in.ShiftReportDayOfWeek != nil {
		in, out := &in.ShiftReportDayOfWeek, &out.ShiftReportDayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportEnabled != nil {
		in, out := &in.ShiftReportEnabled, &out.ShiftReportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftReportTimeOfDay != nil {
		in, out := &in.ShiftReportTimeOfDay, &out.ShiftReportTimeOfDay
		*out = new(string)
		**out = **in
	}
	if in.ShiftReportTimeZone != nil {
		in, out := &in.ShiftReportTimeZone, &out.ShiftReportTimeZone
		*out = new(string)
		**out = **in
	}
	if in.ShiftStartNotificationsEnabled != nil {
		in, out := &in.ShiftStartNotificationsEnabled, &out.ShiftStartNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ShiftUpdateNotificationsEnabled != nil {
		in, out := &in.ShiftUpdateNotificationsEnabled, &out.ShiftUpdateNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SlackChannel != nil {
		in, out := &in.SlackChannel, &out.SlackChannel
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SlackUserGroup != nil {
		in, out := &in.SlackUserGroup, &out.SlackUserGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SyncLinearEnabled != nil {
		in, out := &in.SyncLinearEnabled, &out.SyncLinearEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleParameters.
func (in *ScheduleParameters) DeepCopy() *ScheduleParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleSpec) DeepCopyInto(out *ScheduleSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleSpec.
func (in *ScheduleSpec) DeepCopy() *ScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleStatus) DeepCopyInto(out *ScheduleStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleStatus.
func (in *ScheduleStatus) DeepCopy() *ScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduleStatus)
	in.DeepCopyInto(out)
	return out
}
