// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ScheduleRotation.
func (mg *ScheduleRotation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ScheduleID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ScheduleIDRef,
		Selector:     mg.Spec.ForProvider.ScheduleIDSelector,
		To: reference.To{
			List:    &ScheduleList{},
			Managed: &Schedule{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ScheduleID")
	}
	mg.Spec.ForProvider.ScheduleID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ScheduleIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ScheduleID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ScheduleIDRef,
		Selector:     mg.Spec.InitProvider.ScheduleIDSelector,
		To: reference.To{
			List:    &ScheduleList{},
			Managed: &Schedule{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ScheduleID")
	}
	mg.Spec.InitProvider.ScheduleID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ScheduleIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ScheduleRotationUser.
func (mg *ScheduleRotationUser) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ScheduleRotationID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ScheduleRotationIDRef,
		Selector:     mg.Spec.ForProvider.ScheduleRotationIDSelector,
		To: reference.To{
			List:    &ScheduleRotationList{},
			Managed: &ScheduleRotation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ScheduleRotationID")
	}
	mg.Spec.ForProvider.ScheduleRotationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ScheduleRotationIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ScheduleRotationID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ScheduleRotationIDRef,
		Selector:     mg.Spec.InitProvider.ScheduleRotationIDSelector,
		To: reference.To{
			List:    &ScheduleRotationList{},
			Managed: &ScheduleRotation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ScheduleRotationID")
	}
	mg.Spec.InitProvider.ScheduleRotationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ScheduleRotationIDRef = rsp.ResolvedReference

	return nil
}
