// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ScheduleRotationUserInitParameters struct {

	// Position of the user inside rotation
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// +crossplane:generate:reference:type=github.com/nikogura/provider-rootly/apis/namespaced/schedule/v1alpha1.ScheduleRotation
	ScheduleRotationID *string `json:"scheduleRotationId,omitempty" tf:"schedule_rotation_id,omitempty"`

	// Reference to a ScheduleRotation in schedule to populate scheduleRotationId.
	// +kubebuilder:validation:Optional
	ScheduleRotationIDRef *v2.NamespacedReference `json:"scheduleRotationIdRef,omitempty" tf:"-"`

	// Selector for a ScheduleRotation in schedule to populate scheduleRotationId.
	// +kubebuilder:validation:Optional
	ScheduleRotationIDSelector *v2.NamespacedSelector `json:"scheduleRotationIdSelector,omitempty" tf:"-"`

	// Schedule rotation user
	UserID *float64 `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type ScheduleRotationUserObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Position of the user inside rotation
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	ScheduleRotationID *string `json:"scheduleRotationId,omitempty" tf:"schedule_rotation_id,omitempty"`

	// Schedule rotation user
	UserID *float64 `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type ScheduleRotationUserParameters struct {

	// Position of the user inside rotation
	// +kubebuilder:validation:Optional
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// +crossplane:generate:reference:type=github.com/nikogura/provider-rootly/apis/namespaced/schedule/v1alpha1.ScheduleRotation
	// +kubebuilder:validation:Optional
	ScheduleRotationID *string `json:"scheduleRotationId,omitempty" tf:"schedule_rotation_id,omitempty"`

	// Reference to a ScheduleRotation in schedule to populate scheduleRotationId.
	// +kubebuilder:validation:Optional
	ScheduleRotationIDRef *v2.NamespacedReference `json:"scheduleRotationIdRef,omitempty" tf:"-"`

	// Selector for a ScheduleRotation in schedule to populate scheduleRotationId.
	// +kubebuilder:validation:Optional
	ScheduleRotationIDSelector *v2.NamespacedSelector `json:"scheduleRotationIdSelector,omitempty" tf:"-"`

	// Schedule rotation user
	// +kubebuilder:validation:Optional
	UserID *float64 `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// ScheduleRotationUserSpec defines the desired state of ScheduleRotationUser
type ScheduleRotationUserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ScheduleRotationUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScheduleRotationUserInitParameters `json:"initProvider,omitempty"`
}

// ScheduleRotationUserStatus defines the observed state of ScheduleRotationUser.
type ScheduleRotationUserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ScheduleRotationUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScheduleRotationUser is the Schema for the ScheduleRotationUsers API. One user's position in a schedule rotation. Deprecated upstream in favour of the rotation's inline members.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rootly}
type ScheduleRotationUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userId) || (has(self.initProvider) && has(self.initProvider.userId))",message="spec.forProvider.userId is a required parameter"
	Spec   ScheduleRotationUserSpec   `json:"spec"`
	Status ScheduleRotationUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScheduleRotationUserList contains a list of ScheduleRotationUsers
type ScheduleRotationUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScheduleRotationUser `json:"items"`
}

// Repository type metadata.
var (
	ScheduleRotationUser_Kind             = "ScheduleRotationUser"
	ScheduleRotationUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScheduleRotationUser_Kind}.String()
	ScheduleRotationUser_KindAPIVersion   = ScheduleRotationUser_Kind + "." + CRDGroupVersion.String()
	ScheduleRotationUser_GroupVersionKind = CRDGroupVersion.WithKind(ScheduleRotationUser_Kind)
)

func init() {
	SchemeBuilder.Register(&ScheduleRotationUser{}, &ScheduleRotationUserList{})
}
