// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ScheduleInitParameters struct {

	// 24/7 coverage of the schedule. Value must be one of true or false
	AllTimeCoverage *bool `json:"allTimeCoverage,omitempty" tf:"all_time_coverage,omitempty"`

	// The description of the schedule
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Whether shadow users are included in Slack notifications and user group syncing. Value must be one of true or false
	IncludeShadowsInSlackNotifications *bool `json:"includeShadowsInSlackNotifications,omitempty" tf:"include_shadows_in_slack_notifications,omitempty"`

	// The name of the schedule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The owning teams for this schedules.
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// ID of user assigned as owner of the schedule. Defaults to the API token's user if not specified.
	OwnerUserID *float64 `json:"ownerUserId,omitempty" tf:"owner_user_id,omitempty"`

	// Day of week the weekly shift summary is sent. Value must be one of `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`.
	ShiftReportDayOfWeek *string `json:"shiftReportDayOfWeek,omitempty" tf:"shift_report_day_of_week,omitempty"`

	// Whether the weekly shift summary report is sent. Requires `slack_channel` to be set. Value must be one of true or false
	ShiftReportEnabled *bool `json:"shiftReportEnabled,omitempty" tf:"shift_report_enabled,omitempty"`

	// Time of day the weekly shift summary is sent, in `HH:MM` 24-hour format.
	ShiftReportTimeOfDay *string `json:"shiftReportTimeOfDay,omitempty" tf:"shift_report_time_of_day,omitempty"`

	// IANA time zone used for the weekly shift summary (e.g. `Australia/Sydney`).
	ShiftReportTimeZone *string `json:"shiftReportTimeZone,omitempty" tf:"shift_report_time_zone,omitempty"`

	// Whether to send a Slack message every time a new shift begins. Requires `slack_channel` to be set. Value must be one of true or false
	ShiftStartNotificationsEnabled *bool `json:"shiftStartNotificationsEnabled,omitempty" tf:"shift_start_notifications_enabled,omitempty"`

	// Whether to send a Slack message whenever a shift is updated (overrides, removed users, rotation changes, etc.). Requires `slack_channel` to be set. Value must be one of true or false
	ShiftUpdateNotificationsEnabled *bool `json:"shiftUpdateNotificationsEnabled,omitempty" tf:"shift_update_notifications_enabled,omitempty"`

	// Map must contain two fields, `id` and `name`. Synced slack channel of the schedule
	// +mapType=granular
	SlackChannel map[string]*string `json:"slackChannel,omitempty" tf:"slack_channel,omitempty"`

	// Map must contain two fields, `id` and `name`. Synced slack group of the schedule
	// +mapType=granular
	SlackUserGroup map[string]*string `json:"slackUserGroup,omitempty" tf:"slack_user_group,omitempty"`

	// Whether the schedule is synced with Linear. Value must be one of true or false
	SyncLinearEnabled *bool `json:"syncLinearEnabled,omitempty" tf:"sync_linear_enabled,omitempty"`

	// A valid IANA time zone name. Only applicable when config_one_timezone_per_schedule_enabled is true for the organization.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type ScheduleObservation struct {

	// 24/7 coverage of the schedule. Value must be one of true or false
	AllTimeCoverage *bool `json:"allTimeCoverage,omitempty" tf:"all_time_coverage,omitempty"`

	// The description of the schedule
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether shadow users are included in Slack notifications and user group syncing. Value must be one of true or false
	IncludeShadowsInSlackNotifications *bool `json:"includeShadowsInSlackNotifications,omitempty" tf:"include_shadows_in_slack_notifications,omitempty"`

	// The name of the schedule
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The owning teams for this schedules.
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// ID of user assigned as owner of the schedule. Defaults to the API token's user if not specified.
	OwnerUserID *float64 `json:"ownerUserId,omitempty" tf:"owner_user_id,omitempty"`

	// Day of week the weekly shift summary is sent. Value must be one of `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`.
	ShiftReportDayOfWeek *string `json:"shiftReportDayOfWeek,omitempty" tf:"shift_report_day_of_week,omitempty"`

	// Whether the weekly shift summary report is sent. Requires `slack_channel` to be set. Value must be one of true or false
	ShiftReportEnabled *bool `json:"shiftReportEnabled,omitempty" tf:"shift_report_enabled,omitempty"`

	// Time of day the weekly shift summary is sent, in `HH:MM` 24-hour format.
	ShiftReportTimeOfDay *string `json:"shiftReportTimeOfDay,omitempty" tf:"shift_report_time_of_day,omitempty"`

	// IANA time zone used for the weekly shift summary (e.g. `Australia/Sydney`).
	ShiftReportTimeZone *string `json:"shiftReportTimeZone,omitempty" tf:"shift_report_time_zone,omitempty"`

	// Whether to send a Slack message every time a new shift begins. Requires `slack_channel` to be set. Value must be one of true or false
	ShiftStartNotificationsEnabled *bool `json:"shiftStartNotificationsEnabled,omitempty" tf:"shift_start_notifications_enabled,omitempty"`

	// Whether to send a Slack message whenever a shift is updated (overrides, removed users, rotation changes, etc.). Requires `slack_channel` to be set. Value must be one of true or false
	ShiftUpdateNotificationsEnabled *bool `json:"shiftUpdateNotificationsEnabled,omitempty" tf:"shift_update_notifications_enabled,omitempty"`

	// Map must contain two fields, `id` and `name`. Synced slack channel of the schedule
	// +mapType=granular
	SlackChannel map[string]*string `json:"slackChannel,omitempty" tf:"slack_channel,omitempty"`

	// Map must contain two fields, `id` and `name`. Synced slack group of the schedule
	// +mapType=granular
	SlackUserGroup map[string]*string `json:"slackUserGroup,omitempty" tf:"slack_user_group,omitempty"`

	// Whether the schedule is synced with Linear. Value must be one of true or false
	SyncLinearEnabled *bool `json:"syncLinearEnabled,omitempty" tf:"sync_linear_enabled,omitempty"`

	// A valid IANA time zone name. Only applicable when config_one_timezone_per_schedule_enabled is true for the organization.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type ScheduleParameters struct {

	// 24/7 coverage of the schedule. Value must be one of true or false
	// +kubebuilder:validation:Optional
	AllTimeCoverage *bool `json:"allTimeCoverage,omitempty" tf:"all_time_coverage,omitempty"`

	// The description of the schedule
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Whether shadow users are included in Slack notifications and user group syncing. Value must be one of true or false
	// +kubebuilder:validation:Optional
	IncludeShadowsInSlackNotifications *bool `json:"includeShadowsInSlackNotifications,omitempty" tf:"include_shadows_in_slack_notifications,omitempty"`

	// The name of the schedule
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The owning teams for this schedules.
	// +kubebuilder:validation:Optional
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// ID of user assigned as owner of the schedule. Defaults to the API token's user if not specified.
	// +kubebuilder:validation:Optional
	OwnerUserID *float64 `json:"ownerUserId,omitempty" tf:"owner_user_id,omitempty"`

	// Day of week the weekly shift summary is sent. Value must be one of `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`.
	// +kubebuilder:validation:Optional
	ShiftReportDayOfWeek *string `json:"shiftReportDayOfWeek,omitempty" tf:"shift_report_day_of_week,omitempty"`

	// Whether the weekly shift summary report is sent. Requires `slack_channel` to be set. Value must be one of true or false
	// +kubebuilder:validation:Optional
	ShiftReportEnabled *bool `json:"shiftReportEnabled,omitempty" tf:"shift_report_enabled,omitempty"`

	// Time of day the weekly shift summary is sent, in `HH:MM` 24-hour format.
	// +kubebuilder:validation:Optional
	ShiftReportTimeOfDay *string `json:"shiftReportTimeOfDay,omitempty" tf:"shift_report_time_of_day,omitempty"`

	// IANA time zone used for the weekly shift summary (e.g. `Australia/Sydney`).
	// +kubebuilder:validation:Optional
	ShiftReportTimeZone *string `json:"shiftReportTimeZone,omitempty" tf:"shift_report_time_zone,omitempty"`

	// Whether to send a Slack message every time a new shift begins. Requires `slack_channel` to be set. Value must be one of true or false
	// +kubebuilder:validation:Optional
	ShiftStartNotificationsEnabled *bool `json:"shiftStartNotificationsEnabled,omitempty" tf:"shift_start_notifications_enabled,omitempty"`

	// Whether to send a Slack message whenever a shift is updated (overrides, removed users, rotation changes, etc.). Requires `slack_channel` to be set. Value must be one of true or false
	// +kubebuilder:validation:Optional
	ShiftUpdateNotificationsEnabled *bool `json:"shiftUpdateNotificationsEnabled,omitempty" tf:"shift_update_notifications_enabled,omitempty"`

	// Map must contain two fields, `id` and `name`. Synced slack channel of the schedule
	// +kubebuilder:validation:Optional
	// +mapType=granular
	SlackChannel map[string]*string `json:"slackChannel,omitempty" tf:"slack_channel,omitempty"`

	// Map must contain two fields, `id` and `name`. Synced slack group of the schedule
	// +kubebuilder:validation:Optional
	// +mapType=granular
	SlackUserGroup map[string]*string `json:"slackUserGroup,omitempty" tf:"slack_user_group,omitempty"`

	// Whether the schedule is synced with Linear. Value must be one of true or false
	// +kubebuilder:validation:Optional
	SyncLinearEnabled *bool `json:"syncLinearEnabled,omitempty" tf:"sync_linear_enabled,omitempty"`

	// A valid IANA time zone name. Only applicable when config_one_timezone_per_schedule_enabled is true for the organization.
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

// ScheduleSpec defines the desired state of Schedule
type ScheduleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ScheduleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScheduleInitParameters `json:"initProvider,omitempty"`
}

// ScheduleStatus defines the observed state of Schedule.
type ScheduleStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ScheduleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Schedule is the Schema for the Schedules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rootly}
type Schedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ScheduleSpec   `json:"spec"`
	Status ScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScheduleList contains a list of Schedules
type ScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Schedule `json:"items"`
}

// Repository type metadata.
var (
	Schedule_Kind             = "Schedule"
	Schedule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Schedule_Kind}.String()
	Schedule_KindAPIVersion   = Schedule_Kind + "." + CRDGroupVersion.String()
	Schedule_GroupVersionKind = CRDGroupVersion.WithKind(Schedule_Kind)
)

func init() {
	SchemeBuilder.Register(&Schedule{}, &ScheduleList{})
}
