// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this EscalationLevel.
func (mg *EscalationLevel) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EscalationPolicyID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.EscalationPolicyIDRef,
		Selector:     mg.Spec.ForProvider.EscalationPolicyIDSelector,
		To: reference.To{
			List:    &EscalationPolicyList{},
			Managed: &EscalationPolicy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EscalationPolicyID")
	}
	mg.Spec.ForProvider.EscalationPolicyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EscalationPolicyIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EscalationPolicyID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.EscalationPolicyIDRef,
		Selector:     mg.Spec.InitProvider.EscalationPolicyIDSelector,
		To: reference.To{
			List:    &EscalationPolicyList{},
			Managed: &EscalationPolicy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.EscalationPolicyID")
	}
	mg.Spec.InitProvider.EscalationPolicyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EscalationPolicyIDRef = rsp.ResolvedReference

	return nil
}
