//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Heartbeat) DeepCopyInto(out *Heartbeat) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Heartbeat.
func (in *Heartbeat) DeepCopy() *Heartbeat {
	if in == nil {
		return nil
	}
	out := new(Heartbeat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Heartbeat) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatInitParameters) DeepCopyInto(out *HeartbeatInitParameters) {
	*out = *in
	if in.AlertDescription != nil {
		in, out := &in.AlertDescription, &out.AlertDescription
		*out = new(string)
		**out = **in
	}
	if in.AlertSummary != nil {
		in, out := &in.AlertSummary, &out.AlertSummary
		*out = new(string)
		**out = **in
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EmailAddress != nil {
		in, out := &in.EmailAddress, &out.EmailAddress
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IntervalUnit != nil {
		in, out := &in.IntervalUnit, &out.IntervalUnit
		*out = new(string)
		**out = **in
	}
	if in.LastPingedAt != nil {
		in, out := &in.LastPingedAt, &out.LastPingedAt
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetID != nil {
		in, out := &in.NotificationTargetID, &out.NotificationTargetID
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetType != nil {
		in, out := &in.NotificationTargetType, &out.NotificationTargetType
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatInitParameters.
func (in *HeartbeatInitParameters) DeepCopy() *HeartbeatInitParameters {
	if in == nil {
		return nil
	}
	out := new(HeartbeatInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatList) DeepCopyInto(out *HeartbeatList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Heartbeat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatList.
func (in *HeartbeatList) DeepCopy() *HeartbeatList {
	if in == nil {
		return nil
	}
	out := new(HeartbeatList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeartbeatList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatObservation) DeepCopyInto(out *HeartbeatObservation) {
	*out = *in
	if in.AlertDescription != nil {
		in, out := &in.AlertDescription, &out.AlertDescription
		*out = new(string)
		**out = **in
	}
	if in.AlertSummary != nil {
		in, out := &in.AlertSummary, &out.AlertSummary
		*out = new(string)
		**out = **in
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EmailAddress != nil {
		in, out := &in.EmailAddress, &out.EmailAddress
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IntervalUnit != nil {
		in, out := &in.IntervalUnit, &out.IntervalUnit
		*out = new(string)
		**out = **in
	}
	if in.LastPingedAt != nil {
		in, out := &in.LastPingedAt, &out.LastPingedAt
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetID != nil {
		in, out := &in.NotificationTargetID, &out.NotificationTargetID
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetType != nil {
		in, out := &in.NotificationTargetType, &out.NotificationTargetType
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PingURL != nil {
		in, out := &in.PingURL, &out.PingURL
		*out = new(string)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatObservation.
func (in *HeartbeatObservation) DeepCopy() *HeartbeatObservation {
	if in == nil {
		return nil
	}
	out := new(HeartbeatObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatParameters) DeepCopyInto(out *HeartbeatParameters) {
	*out = *in
	if in.AlertDescription != nil {
		in, out := &in.AlertDescription, &out.AlertDescription
		*out = new(string)
		**out = **in
	}
	if in.AlertSummary != nil {
		in, out := &in.AlertSummary, &out.AlertSummary
		*out = new(string)
		**out = **in
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EmailAddress != nil {
		in, out := &in.EmailAddress, &out.EmailAddress
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(float64)
		**out = **in
	}
	if in.IntervalUnit != nil {
		in, out := &in.IntervalUnit, &out.IntervalUnit
		*out = new(string)
		**out = **in
	}
	if in.LastPingedAt != nil {
		in, out := &in.LastPingedAt, &out.LastPingedAt
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetID != nil {
		in, out := &in.NotificationTargetID, &out.NotificationTargetID
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetType != nil {
		in, out := &in.NotificationTargetType, &out.NotificationTargetType
		*out = new(string)
		**out = **in
	}
	if in.OwnerGroupIds != nil {
		in, out := &in.OwnerGroupIds, &out.OwnerGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatParameters.
func (in *HeartbeatParameters) DeepCopy() *HeartbeatParameters {
	if in == nil {
		return nil
	}
	out := new(HeartbeatParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatSpec) DeepCopyInto(out *HeartbeatSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatSpec.
func (in *HeartbeatSpec) DeepCopy() *HeartbeatSpec {
	if in == nil {
		return nil
	}
	out := new(HeartbeatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatStatus) DeepCopyInto(out *HeartbeatStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatStatus.
func (in *HeartbeatStatus) DeepCopy() *HeartbeatStatus {
	if in == nil {
		return nil
	}
	out := new(HeartbeatStatus)
	in.DeepCopyInto(out)
	return out
}
