//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertBroadcastChannelInitParameters) DeepCopyInto(out *AlertBroadcastChannelInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertBroadcastChannelInitParameters.
func (in *AlertBroadcastChannelInitParameters) DeepCopy() *AlertBroadcastChannelInitParameters {
	if in == nil {
		return nil
	}
	out := new(AlertBroadcastChannelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertBroadcastChannelObservation) DeepCopyInto(out *AlertBroadcastChannelObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertBroadcastChannelObservation.
func (in *AlertBroadcastChannelObservation) DeepCopy() *AlertBroadcastChannelObservation {
	if in == nil {
		return nil
	}
	out := new(AlertBroadcastChannelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertBroadcastChannelParameters) DeepCopyInto(out *AlertBroadcastChannelParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertBroadcastChannelParameters.
func (in *AlertBroadcastChannelParameters) DeepCopy() *AlertBroadcastChannelParameters {
	if in == nil {
		return nil
	}
	out := new(AlertBroadcastChannelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentBroadcastChannelInitParameters) DeepCopyInto(out *IncidentBroadcastChannelInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentBroadcastChannelInitParameters.
func (in *IncidentBroadcastChannelInitParameters) DeepCopy() *IncidentBroadcastChannelInitParameters {
	if in == nil {
		return nil
	}
	out := new(IncidentBroadcastChannelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentBroadcastChannelObservation) DeepCopyInto(out *IncidentBroadcastChannelObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentBroadcastChannelObservation.
func (in *IncidentBroadcastChannelObservation) DeepCopy() *IncidentBroadcastChannelObservation {
	if in == nil {
		return nil
	}
	out := new(IncidentBroadcastChannelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentBroadcastChannelParameters) DeepCopyInto(out *IncidentBroadcastChannelParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentBroadcastChannelParameters.
func (in *IncidentBroadcastChannelParameters) DeepCopy() *IncidentBroadcastChannelParameters {
	if in == nil {
		return nil
	}
	out := new(IncidentBroadcastChannelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertiesInitParameters) DeepCopyInto(out *PropertiesInitParameters) {
	*out = *in
	if in.CatalogPropertyID != nil {
		in, out := &in.CatalogPropertyID, &out.CatalogPropertyID
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertiesInitParameters.
func (in *PropertiesInitParameters) DeepCopy() *PropertiesInitParameters {
	if in == nil {
		return nil
	}
	out := new(PropertiesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertiesObservation) DeepCopyInto(out *PropertiesObservation) {
	*out = *in
	if in.CatalogPropertyID != nil {
		in, out := &in.CatalogPropertyID, &out.CatalogPropertyID
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertiesObservation.
func (in *PropertiesObservation) DeepCopy() *PropertiesObservation {
	if in == nil {
		return nil
	}
	out := new(PropertiesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertiesParameters) DeepCopyInto(out *PropertiesParameters) {
	*out = *in
	if in.CatalogPropertyID != nil {
		in, out := &in.CatalogPropertyID, &out.CatalogPropertyID
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertiesParameters.
func (in *PropertiesParameters) DeepCopy() *PropertiesParameters {
	if in == nil {
		return nil
	}
	out := new(PropertiesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAliasesInitParameters) DeepCopyInto(out *SlackAliasesInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAliasesInitParameters.
func (in *SlackAliasesInitParameters) DeepCopy() *SlackAliasesInitParameters {
	if in == nil {
		return nil
	}
	out := new(SlackAliasesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAliasesObservation) DeepCopyInto(out *SlackAliasesObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAliasesObservation.
func (in *SlackAliasesObservation) DeepCopy() *SlackAliasesObservation {
	if in == nil {
		return nil
	}
	out := new(SlackAliasesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackAliasesParameters) DeepCopyInto(out *SlackAliasesParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackAliasesParameters.
func (in *SlackAliasesParameters) DeepCopy() *SlackAliasesParameters {
	if in == nil {
		return nil
	}
	out := new(SlackAliasesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelsInitParameters) DeepCopyInto(out *SlackChannelsInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelsInitParameters.
func (in *SlackChannelsInitParameters) DeepCopy() *SlackChannelsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SlackChannelsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelsObservation) DeepCopyInto(out *SlackChannelsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelsObservation.
func (in *SlackChannelsObservation) DeepCopy() *SlackChannelsObservation {
	if in == nil {
		return nil
	}
	out := new(SlackChannelsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelsParameters) DeepCopyInto(out *SlackChannelsParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelsParameters.
func (in *SlackChannelsParameters) DeepCopy() *SlackChannelsParameters {
	if in == nil {
		return nil
	}
	out := new(SlackChannelsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamInitParameters) DeepCopyInto(out *TeamInitParameters) {
	*out = *in
	if in.AdminIds != nil {
		in, out := &in.AdminIds, &out.AdminIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.AlertBroadcastChannel != nil {
		in, out := &in.AlertBroadcastChannel, &out.AlertBroadcastChannel
		*out = make([]AlertBroadcastChannelInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertBroadcastEnabled != nil {
		in, out := &in.AlertBroadcastEnabled, &out.AlertBroadcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.AutoAddMembersWhenAttached != nil {
		in, out := &in.AutoAddMembersWhenAttached, &out.AutoAddMembersWhenAttached
		*out = new(bool)
		**out = **in
	}
	if in.BackstageID != nil {
		in, out := &in.BackstageID, &out.BackstageID
		*out = new(string)
		**out = **in
	}
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.CortexID != nil {
		in, out := &in.CortexID, &out.CortexID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.IncidentBroadcastChannel != nil {
		in, out := &in.IncidentBroadcastChannel, &out.IncidentBroadcastChannel
		*out = make([]IncidentBroadcastChannelInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IncidentBroadcastEnabled != nil {
		in, out := &in.IncidentBroadcastEnabled, &out.IncidentBroadcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NotifyEmails != nil {
		in, out := &in.NotifyEmails, &out.NotifyEmails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OpsgenieID != nil {
		in, out := &in.OpsgenieID, &out.OpsgenieID
		*out = new(string)
		**out = **in
	}
	if in.PagerdutyID != nil {
		in, out := &in.PagerdutyID, &out.PagerdutyID
		*out = new(string)
		**out = **in
	}
	if in.PagerdutyServiceID != nil {
		in, out := &in.PagerdutyServiceID, &out.PagerdutyServiceID
		*out = new(string)
		**out = **in
	}
	if in.PagertreeID != nil {
		in, out := &in.PagertreeID, &out.PagertreeID
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]PropertiesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceNowCiSysID != nil {
		in, out := &in.ServiceNowCiSysID, &out.ServiceNowCiSysID
		*out = new(string)
		**out = **in
	}
	if in.SlackAliases != nil {
		in, out := &in.SlackAliases, &out.SlackAliases
		*out = make([]SlackAliasesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SlackChannels != nil {
		in, out := &in.SlackChannels, &out.SlackChannels
		*out = make([]SlackChannelsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UserIds != nil {
		in, out := &in.UserIds, &out.UserIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.VictorOpsID != nil {
		in, out := &in.VictorOpsID, &out.VictorOpsID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamInitParameters.
func (in *TeamInitParameters) DeepCopy() *TeamInitParameters {
	if in == nil {
		return nil
	}
	out := new(TeamInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamList) DeepCopyInto(out *TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamList.
func (in *TeamList) DeepCopy() *TeamList {
	if in == nil {
		return nil
	}
	out := new(TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamObservation) DeepCopyInto(out *TeamObservation) {
	*out = *in
	if in.AdminIds != nil {
		in, out := &in.AdminIds, &out.AdminIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.AlertBroadcastChannel != nil {
		in, out := &in.AlertBroadcastChannel, &out.AlertBroadcastChannel
		*out = make([]AlertBroadcastChannelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertBroadcastEnabled != nil {
		in, out := &in.AlertBroadcastEnabled, &out.AlertBroadcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.AutoAddMembersWhenAttached != nil {
		in, out := &in.AutoAddMembersWhenAttached, &out.AutoAddMembersWhenAttached
		*out = new(bool)
		**out = **in
	}
	if in.BackstageID != nil {
		in, out := &in.BackstageID, &out.BackstageID
		*out = new(string)
		**out = **in
	}
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.CortexID != nil {
		in, out := &in.CortexID, &out.CortexID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncidentBroadcastChannel != nil {
		in, out := &in.IncidentBroadcastChannel, &out.IncidentBroadcastChannel
		*out = make([]IncidentBroadcastChannelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IncidentBroadcastEnabled != nil {
		in, out := &in.IncidentBroadcastEnabled, &out.IncidentBroadcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NotifyEmails != nil {
		in, out := &in.NotifyEmails, &out.NotifyEmails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OpsgenieID != nil {
		in, out := &in.OpsgenieID, &out.OpsgenieID
		*out = new(string)
		**out = **in
	}
	if in.PagerdutyID != nil {
		in, out := &in.PagerdutyID, &out.PagerdutyID
		*out = new(string)
		**out = **in
	}
	if in.PagerdutyServiceID != nil {
		in, out := &in.PagerdutyServiceID, &out.PagerdutyServiceID
		*out = new(string)
		**out = **in
	}
	if in.PagertreeID != nil {
		in, out := &in.PagertreeID, &out.PagertreeID
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]PropertiesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceNowCiSysID != nil {
		in, out := &in.ServiceNowCiSysID, &out.ServiceNowCiSysID
		*out = new(string)
		**out = **in
	}
	if in.SlackAliases != nil {
		in, out := &in.SlackAliases, &out.SlackAliases
		*out = make([]SlackAliasesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SlackChannels != nil {
		in, out := &in.SlackChannels, &out.SlackChannels
		*out = make([]SlackChannelsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UserIds != nil {
		in, out := &in.UserIds, &out.UserIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.VictorOpsID != nil {
		in, out := &in.VictorOpsID, &out.VictorOpsID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamObservation.
func (in *TeamObservation) DeepCopy() *TeamObservation {
	if in == nil {
		return nil
	}
	out := new(TeamObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamParameters) DeepCopyInto(out *TeamParameters) {
	*out = *in
	if in.AdminIds != nil {
		in, out := &in.AdminIds, &out.AdminIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.AlertBroadcastChannel != nil {
		in, out := &in.AlertBroadcastChannel, &out.AlertBroadcastChannel
		*out = make([]AlertBroadcastChannelParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertBroadcastEnabled != nil {
		in, out := &in.AlertBroadcastEnabled, &out.AlertBroadcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AlertUrgencyID != nil {
		in, out := &in.AlertUrgencyID, &out.AlertUrgencyID
		*out = new(string)
		**out = **in
	}
	if in.AutoAddMembersWhenAttached != nil {
		in, out := &in.AutoAddMembersWhenAttached, &out.AutoAddMembersWhenAttached
		*out = new(bool)
		**out = **in
	}
	if in.BackstageID != nil {
		in, out := &in.BackstageID, &out.BackstageID
		*out = new(string)
		**out = **in
	}
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.CortexID != nil {
		in, out := &in.CortexID, &out.CortexID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.IncidentBroadcastChannel != nil {
		in, out := &in.IncidentBroadcastChannel, &out.IncidentBroadcastChannel
		*out = make([]IncidentBroadcastChannelParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IncidentBroadcastEnabled != nil {
		in, out := &in.IncidentBroadcastEnabled, &out.IncidentBroadcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NotifyEmails != nil {
		in, out := &in.NotifyEmails, &out.NotifyEmails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OpsgenieID != nil {
		in, out := &in.OpsgenieID, &out.OpsgenieID
		*out = new(string)
		**out = **in
	}
	if in.PagerdutyID != nil {
		in, out := &in.PagerdutyID, &out.PagerdutyID
		*out = new(string)
		**out = **in
	}
	if in.PagerdutyServiceID != nil {
		in, out := &in.PagerdutyServiceID, &out.PagerdutyServiceID
		*out = new(string)
		**out = **in
	}
	if in.PagertreeID != nil {
		in, out := &in.PagertreeID, &out.PagertreeID
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]PropertiesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceNowCiSysID != nil {
		in, out := &in.ServiceNowCiSysID, &out.ServiceNowCiSysID
		*out = new(string)
		**out = **in
	}
	if in.SlackAliases != nil {
		in, out := &in.SlackAliases, &out.SlackAliases
		*out = make([]SlackAliasesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SlackChannels != nil {
		in, out := &in.SlackChannels, &out.SlackChannels
		*out = make([]SlackChannelsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UserIds != nil {
		in, out := &in.UserIds, &out.UserIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.VictorOpsID != nil {
		in, out := &in.VictorOpsID, &out.VictorOpsID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamParameters.
func (in *TeamParameters) DeepCopy() *TeamParameters {
	if in == nil {
		return nil
	}
	out := new(TeamParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpec.
func (in *TeamSpec) DeepCopy() *TeamSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamStatus.
func (in *TeamStatus) DeepCopy() *TeamStatus {
	if in == nil {
		return nil
	}
	out := new(TeamStatus)
	in.DeepCopyInto(out)
	return out
}
