// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EscalationLevelInitParameters struct {

	// Delay before notifying targets in the next Escalation Level.
	Delay *float64 `json:"delay,omitempty" tf:"delay,omitempty"`

	// The ID of the escalation policy
	// +crossplane:generate:reference:type=github.com/nikogura/provider-rootly/apis/cluster/escalation/v1alpha1.EscalationPolicy
	EscalationPolicyID *string `json:"escalationPolicyId,omitempty" tf:"escalation_policy_id,omitempty"`

	// Reference to a EscalationPolicy in escalation to populate escalationPolicyId.
	// +kubebuilder:validation:Optional
	EscalationPolicyIDRef *v2.Reference `json:"escalationPolicyIdRef,omitempty" tf:"-"`

	// Selector for a EscalationPolicy in escalation to populate escalationPolicyId.
	// +kubebuilder:validation:Optional
	EscalationPolicyIDSelector *v2.Selector `json:"escalationPolicyIdSelector,omitempty" tf:"-"`

	// The ID of the dynamic escalation policy path the level will belong to. If nothing is specified it will add the level to your default path.
	EscalationPolicyPathID *string `json:"escalationPolicyPathId,omitempty" tf:"escalation_policy_path_id,omitempty"`

	// Escalation level's notification targets
	NotificationTargetParams []NotificationTargetParamsInitParameters `json:"notificationTargetParams,omitempty" tf:"notification_target_params,omitempty"`

	// Number of users to page at a time (cycle-based round robin).
	PagingStrategyConfigurationPageUsersCount *float64 `json:"pagingStrategyConfigurationPageUsersCount,omitempty" tf:"paging_strategy_configuration_page_users_count,omitempty"`

	// Number of times to rotate through the roster (cycle-based round robin).
	PagingStrategyConfigurationRepeats *float64 `json:"pagingStrategyConfigurationRepeats,omitempty" tf:"paging_strategy_configuration_repeats,omitempty"`

	// Controls how repeats are interpreted: 'users' pages exactly N users, 'all' pages everyone once.. Value must be one of `users`, `all`.
	PagingStrategyConfigurationRepeatsMode *string `json:"pagingStrategyConfigurationRepeatsMode,omitempty" tf:"paging_strategy_configuration_repeats_mode,omitempty"`

	// Scope of rotation ordering: active rotation members only, or entire schedule.. Value must be one of `active_rotation`, `entire_schedule`.
	PagingStrategyConfigurationRotationScope *string `json:"pagingStrategyConfigurationRotationScope,omitempty" tf:"paging_strategy_configuration_rotation_scope,omitempty"`

	// Value must be one of `on_call_only`, `everyone`.
	PagingStrategyConfigurationScheduleStrategy *string `json:"pagingStrategyConfigurationScheduleStrategy,omitempty" tf:"paging_strategy_configuration_schedule_strategy,omitempty"`

	// Value must be one of `default`, `random`, `cycle`, `alert`.
	PagingStrategyConfigurationStrategy *string `json:"pagingStrategyConfigurationStrategy,omitempty" tf:"paging_strategy_configuration_strategy,omitempty"`

	// Position of the escalation policy level
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type EscalationLevelObservation struct {

	// Delay before notifying targets in the next Escalation Level.
	Delay *float64 `json:"delay,omitempty" tf:"delay,omitempty"`

	// The ID of the escalation policy
	EscalationPolicyID *string `json:"escalationPolicyId,omitempty" tf:"escalation_policy_id,omitempty"`

	// The ID of the dynamic escalation policy path the level will belong to. If nothing is specified it will add the level to your default path.
	EscalationPolicyPathID *string `json:"escalationPolicyPathId,omitempty" tf:"escalation_policy_path_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Escalation level's notification targets
	NotificationTargetParams []NotificationTargetParamsObservation `json:"notificationTargetParams,omitempty" tf:"notification_target_params,omitempty"`

	// Number of users to page at a time (cycle-based round robin).
	PagingStrategyConfigurationPageUsersCount *float64 `json:"pagingStrategyConfigurationPageUsersCount,omitempty" tf:"paging_strategy_configuration_page_users_count,omitempty"`

	// Number of times to rotate through the roster (cycle-based round robin).
	PagingStrategyConfigurationRepeats *float64 `json:"pagingStrategyConfigurationRepeats,omitempty" tf:"paging_strategy_configuration_repeats,omitempty"`

	// Controls how repeats are interpreted: 'users' pages exactly N users, 'all' pages everyone once.. Value must be one of `users`, `all`.
	PagingStrategyConfigurationRepeatsMode *string `json:"pagingStrategyConfigurationRepeatsMode,omitempty" tf:"paging_strategy_configuration_repeats_mode,omitempty"`

	// Scope of rotation ordering: active rotation members only, or entire schedule.. Value must be one of `active_rotation`, `entire_schedule`.
	PagingStrategyConfigurationRotationScope *string `json:"pagingStrategyConfigurationRotationScope,omitempty" tf:"paging_strategy_configuration_rotation_scope,omitempty"`

	// Value must be one of `on_call_only`, `everyone`.
	PagingStrategyConfigurationScheduleStrategy *string `json:"pagingStrategyConfigurationScheduleStrategy,omitempty" tf:"paging_strategy_configuration_schedule_strategy,omitempty"`

	// Value must be one of `default`, `random`, `cycle`, `alert`.
	PagingStrategyConfigurationStrategy *string `json:"pagingStrategyConfigurationStrategy,omitempty" tf:"paging_strategy_configuration_strategy,omitempty"`

	// Position of the escalation policy level
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type EscalationLevelParameters struct {

	// Delay before notifying targets in the next Escalation Level.
	// +kubebuilder:validation:Optional
	Delay *float64 `json:"delay,omitempty" tf:"delay,omitempty"`

	// The ID of the escalation policy
	// +crossplane:generate:reference:type=github.com/nikogura/provider-rootly/apis/cluster/escalation/v1alpha1.EscalationPolicy
	// +kubebuilder:validation:Optional
	EscalationPolicyID *string `json:"escalationPolicyId,omitempty" tf:"escalation_policy_id,omitempty"`

	// Reference to a EscalationPolicy in escalation to populate escalationPolicyId.
	// +kubebuilder:validation:Optional
	EscalationPolicyIDRef *v2.Reference `json:"escalationPolicyIdRef,omitempty" tf:"-"`

	// Selector for a EscalationPolicy in escalation to populate escalationPolicyId.
	// +kubebuilder:validation:Optional
	EscalationPolicyIDSelector *v2.Selector `json:"escalationPolicyIdSelector,omitempty" tf:"-"`

	// The ID of the dynamic escalation policy path the level will belong to. If nothing is specified it will add the level to your default path.
	// +kubebuilder:validation:Optional
	EscalationPolicyPathID *string `json:"escalationPolicyPathId,omitempty" tf:"escalation_policy_path_id,omitempty"`

	// Escalation level's notification targets
	// +kubebuilder:validation:Optional
	NotificationTargetParams []NotificationTargetParamsParameters `json:"notificationTargetParams,omitempty" tf:"notification_target_params,omitempty"`

	// Number of users to page at a time (cycle-based round robin).
	// +kubebuilder:validation:Optional
	PagingStrategyConfigurationPageUsersCount *float64 `json:"pagingStrategyConfigurationPageUsersCount,omitempty" tf:"paging_strategy_configuration_page_users_count,omitempty"`

	// Number of times to rotate through the roster (cycle-based round robin).
	// +kubebuilder:validation:Optional
	PagingStrategyConfigurationRepeats *float64 `json:"pagingStrategyConfigurationRepeats,omitempty" tf:"paging_strategy_configuration_repeats,omitempty"`

	// Controls how repeats are interpreted: 'users' pages exactly N users, 'all' pages everyone once.. Value must be one of `users`, `all`.
	// +kubebuilder:validation:Optional
	PagingStrategyConfigurationRepeatsMode *string `json:"pagingStrategyConfigurationRepeatsMode,omitempty" tf:"paging_strategy_configuration_repeats_mode,omitempty"`

	// Scope of rotation ordering: active rotation members only, or entire schedule.. Value must be one of `active_rotation`, `entire_schedule`.
	// +kubebuilder:validation:Optional
	PagingStrategyConfigurationRotationScope *string `json:"pagingStrategyConfigurationRotationScope,omitempty" tf:"paging_strategy_configuration_rotation_scope,omitempty"`

	// Value must be one of `on_call_only`, `everyone`.
	// +kubebuilder:validation:Optional
	PagingStrategyConfigurationScheduleStrategy *string `json:"pagingStrategyConfigurationScheduleStrategy,omitempty" tf:"paging_strategy_configuration_schedule_strategy,omitempty"`

	// Value must be one of `default`, `random`, `cycle`, `alert`.
	// +kubebuilder:validation:Optional
	PagingStrategyConfigurationStrategy *string `json:"pagingStrategyConfigurationStrategy,omitempty" tf:"paging_strategy_configuration_strategy,omitempty"`

	// Position of the escalation policy level
	// +kubebuilder:validation:Optional
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type NotificationTargetParamsInitParameters struct {

	// The ID of notification target
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// For targets with type=team, controls whether to notify admins, all team members, or escalate to team EP.. Value must be one of `all`, `admins`, `escalate`.
	TeamMembers *string `json:"teamMembers,omitempty" tf:"team_members,omitempty"`

	// The type of the notification target. Value must be one of `team`, `user`, `schedule`, `slack_channel`, `microsoft_teams_channel`, `service`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NotificationTargetParamsObservation struct {

	// The ID of notification target
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// For targets with type=team, controls whether to notify admins, all team members, or escalate to team EP.. Value must be one of `all`, `admins`, `escalate`.
	TeamMembers *string `json:"teamMembers,omitempty" tf:"team_members,omitempty"`

	// The type of the notification target. Value must be one of `team`, `user`, `schedule`, `slack_channel`, `microsoft_teams_channel`, `service`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NotificationTargetParamsParameters struct {

	// The ID of notification target
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// For targets with type=team, controls whether to notify admins, all team members, or escalate to team EP.. Value must be one of `all`, `admins`, `escalate`.
	// +kubebuilder:validation:Optional
	TeamMembers *string `json:"teamMembers,omitempty" tf:"team_members,omitempty"`

	// The type of the notification target. Value must be one of `team`, `user`, `schedule`, `slack_channel`, `microsoft_teams_channel`, `service`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// EscalationLevelSpec defines the desired state of EscalationLevel
type EscalationLevelSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   EscalationLevelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EscalationLevelInitParameters `json:"initProvider,omitempty"`
}

// EscalationLevelStatus defines the observed state of EscalationLevel.
type EscalationLevelStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               EscalationLevelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EscalationLevel is the Schema for the EscalationLevels API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rootly}
type EscalationLevel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.notificationTargetParams) || (has(self.initProvider) && has(self.initProvider.notificationTargetParams))",message="spec.forProvider.notificationTargetParams is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.position) || (has(self.initProvider) && has(self.initProvider.position))",message="spec.forProvider.position is a required parameter"
	Spec   EscalationLevelSpec   `json:"spec"`
	Status EscalationLevelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EscalationLevelList contains a list of EscalationLevels
type EscalationLevelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EscalationLevel `json:"items"`
}

// Repository type metadata.
var (
	EscalationLevel_Kind             = "EscalationLevel"
	EscalationLevel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EscalationLevel_Kind}.String()
	EscalationLevel_KindAPIVersion   = EscalationLevel_Kind + "." + CRDGroupVersion.String()
	EscalationLevel_GroupVersionKind = CRDGroupVersion.WithKind(EscalationLevel_Kind)
)

func init() {
	SchemeBuilder.Register(&EscalationLevel{}, &EscalationLevelList{})
}
