//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BusinessHoursInitParameters) DeepCopyInto(out *BusinessHoursInitParameters) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BusinessHoursInitParameters.
func (in *BusinessHoursInitParameters) DeepCopy() *BusinessHoursInitParameters {
	if in == nil {
		return nil
	}
	out := new(BusinessHoursInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BusinessHoursObservation) DeepCopyInto(out *BusinessHoursObservation) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BusinessHoursObservation.
func (in *BusinessHoursObservation) DeepCopy() *BusinessHoursObservation {
	if in == nil {
		return nil
	}
	out := new(BusinessHoursObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BusinessHoursParameters) DeepCopyInto(out *BusinessHoursParameters) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BusinessHoursParameters.
func (in *BusinessHoursParameters) DeepCopy() *BusinessHoursParameters {
	if in == nil {
		return nil
	}
	out := new(BusinessHoursParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationLevel) DeepCopyInto(out *EscalationLevel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationLevel.
func (in *EscalationLevel) DeepCopy() *EscalationLevel {
	if in == nil {
		return nil
	}
	out := new(EscalationLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EscalationLevel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationLevelInitParameters) DeepCopyInto(out *EscalationLevelInitParameters) {
	*out = *in
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(float64)
		**out = **in
	}
	if in.EscalationPolicyID != nil {
		in, out := &in.EscalationPolicyID, &out.EscalationPolicyID
		*out = new(string)
		**out = **in
	}
	if in.EscalationPolicyIDRef != nil {
		in, out := &in.EscalationPolicyIDRef, &out.EscalationPolicyIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EscalationPolicyIDSelector != nil {
		in, out := &in.EscalationPolicyIDSelector, &out.EscalationPolicyIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EscalationPolicyPathID != nil {
		in, out := &in.EscalationPolicyPathID, &out.EscalationPolicyPathID
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetParams != nil {
		in, out := &in.NotificationTargetParams, &out.NotificationTargetParams
		*out = make([]NotificationTargetParamsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PagingStrategyConfigurationPageUsersCount != nil {
		in, out := &in.PagingStrategyConfigurationPageUsersCount, &out.PagingStrategyConfigurationPageUsersCount
		*out = new(float64)
		**out = **in
	}
	if in.PagingStrategyConfigurationRepeats != nil {
		in, out := &in.PagingStrategyConfigurationRepeats, &out.PagingStrategyConfigurationRepeats
		*out = new(float64)
		**out = **in
	}
	if in.PagingStrategyConfigurationRepeatsMode != nil {
		in, out := &in.PagingStrategyConfigurationRepeatsMode, &out.PagingStrategyConfigurationRepeatsMode
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationRotationScope != nil {
		in, out := &in.PagingStrategyConfigurationRotationScope, &out.PagingStrategyConfigurationRotationScope
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationScheduleStrategy != nil {
		in, out := &in.PagingStrategyConfigurationScheduleStrategy, &out.PagingStrategyConfigurationScheduleStrategy
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationStrategy != nil {
		in, out := &in.PagingStrategyConfigurationStrategy, &out.PagingStrategyConfigurationStrategy
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationLevelInitParameters.
func (in *EscalationLevelInitParameters) DeepCopy() *EscalationLevelInitParameters {
	if in == nil {
		return nil
	}
	out := new(EscalationLevelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationLevelList) DeepCopyInto(out *EscalationLevelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EscalationLevel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationLevelList.
func (in *EscalationLevelList) DeepCopy() *EscalationLevelList {
	if in == nil {
		return nil
	}
	out := new(EscalationLevelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EscalationLevelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationLevelObservation) DeepCopyInto(out *EscalationLevelObservation) {
	*out = *in
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(float64)
		**out = **in
	}
	if in.EscalationPolicyID != nil {
		in, out := &in.EscalationPolicyID, &out.EscalationPolicyID
		*out = new(string)
		**out = **in
	}
	if in.EscalationPolicyPathID != nil {
		in, out := &in.EscalationPolicyPathID, &out.EscalationPolicyPathID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetParams != nil {
		in, out := &in.NotificationTargetParams, &out.NotificationTargetParams
		*out = make([]NotificationTargetParamsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PagingStrategyConfigurationPageUsersCount != nil {
		in, out := &in.PagingStrategyConfigurationPageUsersCount, &out.PagingStrategyConfigurationPageUsersCount
		*out = new(float64)
		**out = **in
	}
	if in.PagingStrategyConfigurationRepeats != nil {
		in, out := &in.PagingStrategyConfigurationRepeats, &out.PagingStrategyConfigurationRepeats
		*out = new(float64)
		**out = **in
	}
	if in.PagingStrategyConfigurationRepeatsMode != nil {
		in, out := &in.PagingStrategyConfigurationRepeatsMode, &out.PagingStrategyConfigurationRepeatsMode
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationRotationScope != nil {
		in, out := &in.PagingStrategyConfigurationRotationScope, &out.PagingStrategyConfigurationRotationScope
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationScheduleStrategy != nil {
		in, out := &in.PagingStrategyConfigurationScheduleStrategy, &out.PagingStrategyConfigurationScheduleStrategy
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationStrategy != nil {
		in, out := &in.PagingStrategyConfigurationStrategy, &out.PagingStrategyConfigurationStrategy
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationLevelObservation.
func (in *EscalationLevelObservation) DeepCopy() *EscalationLevelObservation {
	if in == nil {
		return nil
	}
	out := new(EscalationLevelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationLevelParameters) DeepCopyInto(out *EscalationLevelParameters) {
	*out = *in
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(float64)
		**out = **in
	}
	if in.EscalationPolicyID != nil {
		in, out := &in.EscalationPolicyID, &out.EscalationPolicyID
		*out = new(string)
		**out = **in
	}
	if in.EscalationPolicyIDRef != nil {
		in, out := &in.EscalationPolicyIDRef, &out.EscalationPolicyIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EscalationPolicyIDSelector != nil {
		in, out := &in.EscalationPolicyIDSelector, &out.EscalationPolicyIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EscalationPolicyPathID != nil {
		in, out := &in.EscalationPolicyPathID, &out.EscalationPolicyPathID
		*out = new(string)
		**out = **in
	}
	if in.NotificationTargetParams != nil {
		in, out := &in.NotificationTargetParams, &out.NotificationTargetParams
		*out = make([]NotificationTargetParamsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PagingStrategyConfigurationPageUsersCount != nil {
		in, out := &in.PagingStrategyConfigurationPageUsersCount, &out.PagingStrategyConfigurationPageUsersCount
		*out = new(float64)
		**out = **in
	}
	if in.PagingStrategyConfigurationRepeats != nil {
		in, out := &in.PagingStrategyConfigurationRepeats, &out.PagingStrategyConfigurationRepeats
		*out = new(float64)
		**out = **in
	}
	if in.PagingStrategyConfigurationRepeatsMode != nil {
		in, out := &in.PagingStrategyConfigurationRepeatsMode, &out.PagingStrategyConfigurationRepeatsMode
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationRotationScope != nil {
		in, out := &in.PagingStrategyConfigurationRotationScope, &out.PagingStrategyConfigurationRotationScope
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationScheduleStrategy != nil {
		in, out := &in.PagingStrategyConfigurationScheduleStrategy, &out.PagingStrategyConfigurationScheduleStrategy
		*out = new(string)
		**out = **in
	}
	if in.PagingStrategyConfigurationStrategy != nil {
		in, out := &in.PagingStrategyConfigurationStrategy, &out.PagingStrategyConfigurationStrategy
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationLevelParameters.
func (in *EscalationLevelParameters) DeepCopy() *EscalationLevelParameters {
	if in == nil {
		return nil
	}
	out := new(EscalationLevelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationLevelSpec) DeepCopyInto(out *EscalationLevelSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationLevelSpec.
func (in *EscalationLevelSpec) DeepCopy() *EscalationLevelSpec {
	if in == nil {
		return nil
	}
	out := new(EscalationLevelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationLevelStatus) DeepCopyInto(out *EscalationLevelStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationLevelStatus.
func (in *EscalationLevelStatus) DeepCopy() *EscalationLevelStatus {
	if in == nil {
		return nil
	}
	out := new(EscalationLevelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicy) DeepCopyInto(out *EscalationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicy.
func (in *EscalationPolicy) DeepCopy() *EscalationPolicy {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EscalationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicyInitParameters) DeepCopyInto(out *EscalationPolicyInitParameters) {
	*out = *in
	if in.BusinessHours != nil {
		in, out := &in.BusinessHours, &out.BusinessHours
		*out = make([]BusinessHoursInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedByUserID != nil {
		in, out := &in.CreatedByUserID, &out.CreatedByUserID
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GroupIds != nil {
		in, out := &in.GroupIds, &out.GroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LastUpdatedByUserID != nil {
		in, out := &in.LastUpdatedByUserID, &out.LastUpdatedByUserID
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RepeatCount != nil {
		in, out := &in.RepeatCount, &out.RepeatCount
		*out = new(float64)
		**out = **in
	}
	if in.ServiceIds != nil {
		in, out := &in.ServiceIds, &out.ServiceIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicyInitParameters.
func (in *EscalationPolicyInitParameters) DeepCopy() *EscalationPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicyList) DeepCopyInto(out *EscalationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EscalationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicyList.
func (in *EscalationPolicyList) DeepCopy() *EscalationPolicyList {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EscalationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicyObservation) DeepCopyInto(out *EscalationPolicyObservation) {
	*out = *in
	if in.BusinessHours != nil {
		in, out := &in.BusinessHours, &out.BusinessHours
		*out = make([]BusinessHoursObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedByUserID != nil {
		in, out := &in.CreatedByUserID, &out.CreatedByUserID
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GroupIds != nil {
		in, out := &in.GroupIds, &out.GroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedByUserID != nil {
		in, out := &in.LastUpdatedByUserID, &out.LastUpdatedByUserID
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RepeatCount != nil {
		in, out := &in.RepeatCount, &out.RepeatCount
		*out = new(float64)
		**out = **in
	}
	if in.ServiceIds != nil {
		in, out := &in.ServiceIds, &out.ServiceIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicyObservation.
func (in *EscalationPolicyObservation) DeepCopy() *EscalationPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicyParameters) DeepCopyInto(out *EscalationPolicyParameters) {
	*out = *in
	if in.BusinessHours != nil {
		in, out := &in.BusinessHours, &out.BusinessHours
		*out = make([]BusinessHoursParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedByUserID != nil {
		in, out := &in.CreatedByUserID, &out.CreatedByUserID
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GroupIds != nil {
		in, out := &in.GroupIds, &out.GroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LastUpdatedByUserID != nil {
		in, out := &in.LastUpdatedByUserID, &out.LastUpdatedByUserID
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RepeatCount != nil {
		in, out := &in.RepeatCount, &out.RepeatCount
		*out = new(float64)
		**out = **in
	}
	if in.ServiceIds != nil {
		in, out := &in.ServiceIds, &out.ServiceIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicyParameters.
func (in *EscalationPolicyParameters) DeepCopy() *EscalationPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicySpec) DeepCopyInto(out *EscalationPolicySpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicySpec.
func (in *EscalationPolicySpec) DeepCopy() *EscalationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicyStatus) DeepCopyInto(out *EscalationPolicyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicyStatus.
func (in *EscalationPolicyStatus) DeepCopy() *EscalationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTargetParamsInitParameters) DeepCopyInto(out *NotificationTargetParamsInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.TeamMembers != nil {
		in, out := &in.TeamMembers, &out.TeamMembers
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTargetParamsInitParameters.
func (in *NotificationTargetParamsInitParameters) DeepCopy() *NotificationTargetParamsInitParameters {
	if in == nil {
		return nil
	}
	out := new(NotificationTargetParamsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTargetParamsObservation) DeepCopyInto(out *NotificationTargetParamsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.TeamMembers != nil {
		in, out := &in.TeamMembers, &out.TeamMembers
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTargetParamsObservation.
func (in *NotificationTargetParamsObservation) DeepCopy() *NotificationTargetParamsObservation {
	if in == nil {
		return nil
	}
	out := new(NotificationTargetParamsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTargetParamsParameters) DeepCopyInto(out *NotificationTargetParamsParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.TeamMembers != nil {
		in, out := &in.TeamMembers, &out.TeamMembers
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTargetParamsParameters.
func (in *NotificationTargetParamsParameters) DeepCopy() *NotificationTargetParamsParameters {
	if in == nil {
		return nil
	}
	out := new(NotificationTargetParamsParameters)
	in.DeepCopyInto(out)
	return out
}
