// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ActiveTimeAttributesInitParameters struct {

	// End time for schedule rotation active time.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// Start time for schedule rotation active time.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`
}

type ActiveTimeAttributesObservation struct {

	// End time for schedule rotation active time.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// Start time for schedule rotation active time.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`
}

type ActiveTimeAttributesParameters struct {

	// End time for schedule rotation active time.
	// +kubebuilder:validation:Optional
	EndTime *string `json:"endTime" tf:"end_time,omitempty"`

	// Start time for schedule rotation active time.
	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime" tf:"start_time,omitempty"`
}

type ScheduleRotationInitParameters struct {

	// Schedule rotation active all week?
	ActiveAllWeek *bool `json:"activeAllWeek,omitempty" tf:"active_all_week,omitempty"`

	// Value must be one of `S`, `M`, `T`, `W`, `R`, `F`, `U`.
	// +listType=set
	ActiveDays []*string `json:"activeDays,omitempty" tf:"active_days,omitempty"`

	// Schedule rotation's active times.
	ActiveTimeAttributes []ActiveTimeAttributesInitParameters `json:"activeTimeAttributes,omitempty" tf:"active_time_attributes,omitempty"`

	// Value must be one of `all_day`, `same_time`, or `custom`. The value chosen will override `active_time_attributes` in any `rootly_schedule_rotation_active_day` resources linked to this `rootly_schedule_rotation`.
	ActiveTimeType *string `json:"activeTimeType,omitempty" tf:"active_time_type,omitempty"`

	// ISO8601 date and time when rotation ends. Shifts will only be created before this time.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// The name of the schedule rotation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Position of the schedule rotation.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// The ID of parent schedule.
	// +crossplane:generate:reference:type=github.com/nikogura/provider-rootly/apis/cluster/schedule/v1alpha1.Schedule
	ScheduleID *string `json:"scheduleId,omitempty" tf:"schedule_id,omitempty"`

	// Reference to a Schedule in schedule to populate scheduleId.
	// +kubebuilder:validation:Optional
	ScheduleIDRef *v2.Reference `json:"scheduleIdRef,omitempty" tf:"-"`

	// Selector for a Schedule in schedule to populate scheduleId.
	// +kubebuilder:validation:Optional
	ScheduleIDSelector *v2.Selector `json:"scheduleIdSelector,omitempty" tf:"-"`

	// Schedule rotation members. You can only add schedule rotation members if your account has schedule nesting feature enabled.
	ScheduleRotationMembers []ScheduleRotationMembersInitParameters `json:"scheduleRotationMembers,omitempty" tf:"schedule_rotation_members,omitempty"`

	ScheduleRotationableAttributes *ScheduleRotationableAttributesInitParameters `json:"scheduleRotationableAttributes,omitempty" tf:"schedule_rotationable_attributes,omitempty"`

	// Schedule rotation type. Value must be one of `ScheduleDailyRotation`, `ScheduleWeeklyRotation`, `ScheduleBiweeklyRotation`, `ScheduleMonthlyRotation`, `ScheduleCustomRotation`.
	ScheduleRotationableType *string `json:"scheduleRotationableType,omitempty" tf:"schedule_rotationable_type,omitempty"`

	// ISO8601 date and time when rotation starts. Shifts will only be created after this time.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// A valid IANA time zone name.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type ScheduleRotationMembersInitParameters struct {

	// ID of the member.
	MemberID *string `json:"memberId,omitempty" tf:"member_id,omitempty"`

	// Type of member. Value must be one of `Schedule` or `User`.
	MemberType *string `json:"memberType,omitempty" tf:"member_type,omitempty"`

	// Position of the member in rotation
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type ScheduleRotationMembersObservation struct {

	// ID of the member.
	MemberID *string `json:"memberId,omitempty" tf:"member_id,omitempty"`

	// Type of member. Value must be one of `Schedule` or `User`.
	MemberType *string `json:"memberType,omitempty" tf:"member_type,omitempty"`

	// Position of the member in rotation
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type ScheduleRotationMembersParameters struct {

	// ID of the member.
	// +kubebuilder:validation:Optional
	MemberID *string `json:"memberId" tf:"member_id,omitempty"`

	// Type of member. Value must be one of `Schedule` or `User`.
	// +kubebuilder:validation:Optional
	MemberType *string `json:"memberType" tf:"member_type,omitempty"`

	// Position of the member in rotation
	// +kubebuilder:validation:Optional
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type ScheduleRotationObservation struct {

	// Schedule rotation active all week?
	ActiveAllWeek *bool `json:"activeAllWeek,omitempty" tf:"active_all_week,omitempty"`

	// Value must be one of `S`, `M`, `T`, `W`, `R`, `F`, `U`.
	// +listType=set
	ActiveDays []*string `json:"activeDays,omitempty" tf:"active_days,omitempty"`

	// Schedule rotation's active times.
	ActiveTimeAttributes []ActiveTimeAttributesObservation `json:"activeTimeAttributes,omitempty" tf:"active_time_attributes,omitempty"`

	// Value must be one of `all_day`, `same_time`, or `custom`. The value chosen will override `active_time_attributes` in any `rootly_schedule_rotation_active_day` resources linked to this `rootly_schedule_rotation`.
	ActiveTimeType *string `json:"activeTimeType,omitempty" tf:"active_time_type,omitempty"`

	// ISO8601 date and time when rotation ends. Shifts will only be created before this time.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the schedule rotation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Position of the schedule rotation.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// The ID of parent schedule.
	ScheduleID *string `json:"scheduleId,omitempty" tf:"schedule_id,omitempty"`

	// Schedule rotation members. You can only add schedule rotation members if your account has schedule nesting feature enabled.
	ScheduleRotationMembers []ScheduleRotationMembersObservation `json:"scheduleRotationMembers,omitempty" tf:"schedule_rotation_members,omitempty"`

	ScheduleRotationableAttributes *ScheduleRotationableAttributesObservation `json:"scheduleRotationableAttributes,omitempty" tf:"schedule_rotationable_attributes,omitempty"`

	// Schedule rotation type. Value must be one of `ScheduleDailyRotation`, `ScheduleWeeklyRotation`, `ScheduleBiweeklyRotation`, `ScheduleMonthlyRotation`, `ScheduleCustomRotation`.
	ScheduleRotationableType *string `json:"scheduleRotationableType,omitempty" tf:"schedule_rotationable_type,omitempty"`

	// ISO8601 date and time when rotation starts. Shifts will only be created after this time.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// A valid IANA time zone name.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type ScheduleRotationParameters struct {

	// Schedule rotation active all week?
	// +kubebuilder:validation:Optional
	ActiveAllWeek *bool `json:"activeAllWeek,omitempty" tf:"active_all_week,omitempty"`

	// Value must be one of `S`, `M`, `T`, `W`, `R`, `F`, `U`.
	// +kubebuilder:validation:Optional
	// +listType=set
	ActiveDays []*string `json:"activeDays,omitempty" tf:"active_days,omitempty"`

	// Schedule rotation's active times.
	// +kubebuilder:validation:Optional
	ActiveTimeAttributes []ActiveTimeAttributesParameters `json:"activeTimeAttributes,omitempty" tf:"active_time_attributes,omitempty"`

	// Value must be one of `all_day`, `same_time`, or `custom`. The value chosen will override `active_time_attributes` in any `rootly_schedule_rotation_active_day` resources linked to this `rootly_schedule_rotation`.
	// +kubebuilder:validation:Optional
	ActiveTimeType *string `json:"activeTimeType,omitempty" tf:"active_time_type,omitempty"`

	// ISO8601 date and time when rotation ends. Shifts will only be created before this time.
	// +kubebuilder:validation:Optional
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// The name of the schedule rotation.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Position of the schedule rotation.
	// +kubebuilder:validation:Optional
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// The ID of parent schedule.
	// +crossplane:generate:reference:type=github.com/nikogura/provider-rootly/apis/cluster/schedule/v1alpha1.Schedule
	// +kubebuilder:validation:Optional
	ScheduleID *string `json:"scheduleId,omitempty" tf:"schedule_id,omitempty"`

	// Reference to a Schedule in schedule to populate scheduleId.
	// +kubebuilder:validation:Optional
	ScheduleIDRef *v2.Reference `json:"scheduleIdRef,omitempty" tf:"-"`

	// Selector for a Schedule in schedule to populate scheduleId.
	// +kubebuilder:validation:Optional
	ScheduleIDSelector *v2.Selector `json:"scheduleIdSelector,omitempty" tf:"-"`

	// Schedule rotation members. You can only add schedule rotation members if your account has schedule nesting feature enabled.
	// +kubebuilder:validation:Optional
	ScheduleRotationMembers []ScheduleRotationMembersParameters `json:"scheduleRotationMembers,omitempty" tf:"schedule_rotation_members,omitempty"`

	// +kubebuilder:validation:Optional
	ScheduleRotationableAttributes *ScheduleRotationableAttributesParameters `json:"scheduleRotationableAttributes,omitempty" tf:"schedule_rotationable_attributes,omitempty"`

	// Schedule rotation type. Value must be one of `ScheduleDailyRotation`, `ScheduleWeeklyRotation`, `ScheduleBiweeklyRotation`, `ScheduleMonthlyRotation`, `ScheduleCustomRotation`.
	// +kubebuilder:validation:Optional
	ScheduleRotationableType *string `json:"scheduleRotationableType,omitempty" tf:"schedule_rotationable_type,omitempty"`

	// ISO8601 date and time when rotation starts. Shifts will only be created after this time.
	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// A valid IANA time zone name.
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type ScheduleRotationableAttributesInitParameters struct {

	// Hand off day. Only applicable for weekly/biweekly, and monthly.
	HandoffDay *string `json:"handoffDay,omitempty" tf:"handoff_day,omitempty"`

	// Hand off time. Only applicable for daily, weekly/biweekly, monthly, and custom rotations.
	HandoffTime *string `json:"handoffTime,omitempty" tf:"handoff_time,omitempty"`

	// Shift length for custom rotation.
	ShiftLength *float64 `json:"shiftLength,omitempty" tf:"shift_length,omitempty"`

	// Shift length unit for custom rotation. Value must be one of `hours`, `days`, `weeks`.
	ShiftLengthUnit *string `json:"shiftLengthUnit,omitempty" tf:"shift_length_unit,omitempty"`
}

type ScheduleRotationableAttributesObservation struct {

	// Hand off day. Only applicable for weekly/biweekly, and monthly.
	HandoffDay *string `json:"handoffDay,omitempty" tf:"handoff_day,omitempty"`

	// Hand off time. Only applicable for daily, weekly/biweekly, monthly, and custom rotations.
	HandoffTime *string `json:"handoffTime,omitempty" tf:"handoff_time,omitempty"`

	// Shift length for custom rotation.
	ShiftLength *float64 `json:"shiftLength,omitempty" tf:"shift_length,omitempty"`

	// Shift length unit for custom rotation. Value must be one of `hours`, `days`, `weeks`.
	ShiftLengthUnit *string `json:"shiftLengthUnit,omitempty" tf:"shift_length_unit,omitempty"`
}

type ScheduleRotationableAttributesParameters struct {

	// Hand off day. Only applicable for weekly/biweekly, and monthly.
	// +kubebuilder:validation:Optional
	HandoffDay *string `json:"handoffDay,omitempty" tf:"handoff_day,omitempty"`

	// Hand off time. Only applicable for daily, weekly/biweekly, monthly, and custom rotations.
	// +kubebuilder:validation:Optional
	HandoffTime *string `json:"handoffTime" tf:"handoff_time,omitempty"`

	// Shift length for custom rotation.
	// +kubebuilder:validation:Optional
	ShiftLength *float64 `json:"shiftLength,omitempty" tf:"shift_length,omitempty"`

	// Shift length unit for custom rotation. Value must be one of `hours`, `days`, `weeks`.
	// +kubebuilder:validation:Optional
	ShiftLengthUnit *string `json:"shiftLengthUnit,omitempty" tf:"shift_length_unit,omitempty"`
}

// ScheduleRotationSpec defines the desired state of ScheduleRotation
type ScheduleRotationSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ScheduleRotationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScheduleRotationInitParameters `json:"initProvider,omitempty"`
}

// ScheduleRotationStatus defines the observed state of ScheduleRotation.
type ScheduleRotationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ScheduleRotationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScheduleRotation is the Schema for the ScheduleRotations API. A rotation within a schedule: the shift pattern, the hours it is active, and its members.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rootly}
type ScheduleRotation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scheduleRotationableAttributes) || (has(self.initProvider) && has(self.initProvider.scheduleRotationableAttributes))",message="spec.forProvider.scheduleRotationableAttributes is a required parameter"
	Spec   ScheduleRotationSpec   `json:"spec"`
	Status ScheduleRotationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScheduleRotationList contains a list of ScheduleRotations
type ScheduleRotationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScheduleRotation `json:"items"`
}

// Repository type metadata.
var (
	ScheduleRotation_Kind             = "ScheduleRotation"
	ScheduleRotation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScheduleRotation_Kind}.String()
	ScheduleRotation_KindAPIVersion   = ScheduleRotation_Kind + "." + CRDGroupVersion.String()
	ScheduleRotation_GroupVersionKind = CRDGroupVersion.WithKind(ScheduleRotation_Kind)
)

func init() {
	SchemeBuilder.Register(&ScheduleRotation{}, &ScheduleRotationList{})
}
