// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type HeartbeatInitParameters struct {

	// Description of alerts triggered when heartbeat expires.
	AlertDescription *string `json:"alertDescription,omitempty" tf:"alert_description,omitempty"`

	// Summary of alerts triggered when heartbeat expires.
	AlertSummary *string `json:"alertSummary,omitempty" tf:"alert_summary,omitempty"`

	// Urgency of alerts triggered when heartbeat expires.
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// The description of the heartbeat
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Email address to receive heartbeat pings.
	EmailAddress *string `json:"emailAddress,omitempty" tf:"email_address,omitempty"`

	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// When heartbeat expires
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// Value must be one of `minutes`, `hours`, `days`.
	IntervalUnit *string `json:"intervalUnit,omitempty" tf:"interval_unit,omitempty"`

	// When the heartbeat was last pinged.
	LastPingedAt *string `json:"lastPingedAt,omitempty" tf:"last_pinged_at,omitempty"`

	// The name of the heartbeat
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	NotificationTargetID *string `json:"notificationTargetId,omitempty" tf:"notification_target_id,omitempty"`

	// The type of the notification target. Please contact support if you encounter issues using `Functionality` as a target type.. Value must be one of `User`, `Group`, `Service`, `EscalationPolicy`, `Functionality`.
	NotificationTargetType *string `json:"notificationTargetType,omitempty" tf:"notification_target_type,omitempty"`

	// List of team IDs that own this heartbeat
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// Value must be one of `waiting`, `active`, `expired`.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type HeartbeatObservation struct {

	// Description of alerts triggered when heartbeat expires.
	AlertDescription *string `json:"alertDescription,omitempty" tf:"alert_description,omitempty"`

	// Summary of alerts triggered when heartbeat expires.
	AlertSummary *string `json:"alertSummary,omitempty" tf:"alert_summary,omitempty"`

	// Urgency of alerts triggered when heartbeat expires.
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// The description of the heartbeat
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Email address to receive heartbeat pings.
	EmailAddress *string `json:"emailAddress,omitempty" tf:"email_address,omitempty"`

	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// When heartbeat expires
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// Value must be one of `minutes`, `hours`, `days`.
	IntervalUnit *string `json:"intervalUnit,omitempty" tf:"interval_unit,omitempty"`

	// When the heartbeat was last pinged.
	LastPingedAt *string `json:"lastPingedAt,omitempty" tf:"last_pinged_at,omitempty"`

	// The name of the heartbeat
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	NotificationTargetID *string `json:"notificationTargetId,omitempty" tf:"notification_target_id,omitempty"`

	// The type of the notification target. Please contact support if you encounter issues using `Functionality` as a target type.. Value must be one of `User`, `Group`, `Service`, `EscalationPolicy`, `Functionality`.
	NotificationTargetType *string `json:"notificationTargetType,omitempty" tf:"notification_target_type,omitempty"`

	// List of team IDs that own this heartbeat
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// URL to receive heartbeat pings.
	PingURL *string `json:"pingUrl,omitempty" tf:"ping_url,omitempty"`

	// Secret used as bearer token when pinging heartbeat.
	Secret *string `json:"secret,omitempty" tf:"secret,omitempty"`

	// Value must be one of `waiting`, `active`, `expired`.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type HeartbeatParameters struct {

	// Description of alerts triggered when heartbeat expires.
	// +kubebuilder:validation:Optional
	AlertDescription *string `json:"alertDescription,omitempty" tf:"alert_description,omitempty"`

	// Summary of alerts triggered when heartbeat expires.
	// +kubebuilder:validation:Optional
	AlertSummary *string `json:"alertSummary,omitempty" tf:"alert_summary,omitempty"`

	// Urgency of alerts triggered when heartbeat expires.
	// +kubebuilder:validation:Optional
	AlertUrgencyID *string `json:"alertUrgencyId,omitempty" tf:"alert_urgency_id,omitempty"`

	// The description of the heartbeat
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Email address to receive heartbeat pings.
	// +kubebuilder:validation:Optional
	EmailAddress *string `json:"emailAddress,omitempty" tf:"email_address,omitempty"`

	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// When heartbeat expires
	// +kubebuilder:validation:Optional
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// Value must be one of `minutes`, `hours`, `days`.
	// +kubebuilder:validation:Optional
	IntervalUnit *string `json:"intervalUnit,omitempty" tf:"interval_unit,omitempty"`

	// When the heartbeat was last pinged.
	// +kubebuilder:validation:Optional
	LastPingedAt *string `json:"lastPingedAt,omitempty" tf:"last_pinged_at,omitempty"`

	// The name of the heartbeat
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	NotificationTargetID *string `json:"notificationTargetId,omitempty" tf:"notification_target_id,omitempty"`

	// The type of the notification target. Please contact support if you encounter issues using `Functionality` as a target type.. Value must be one of `User`, `Group`, `Service`, `EscalationPolicy`, `Functionality`.
	// +kubebuilder:validation:Optional
	NotificationTargetType *string `json:"notificationTargetType,omitempty" tf:"notification_target_type,omitempty"`

	// List of team IDs that own this heartbeat
	// +kubebuilder:validation:Optional
	OwnerGroupIds []*string `json:"ownerGroupIds,omitempty" tf:"owner_group_ids,omitempty"`

	// Value must be one of `waiting`, `active`, `expired`.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

// HeartbeatSpec defines the desired state of Heartbeat
type HeartbeatSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            HeartbeatParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HeartbeatInitParameters `json:"initProvider,omitempty"`
}

// HeartbeatStatus defines the observed state of Heartbeat.
type HeartbeatStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               HeartbeatObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Heartbeat is the Schema for the Heartbeats API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rootly}
type Heartbeat struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alertSummary) || (has(self.initProvider) && has(self.initProvider.alertSummary))",message="spec.forProvider.alertSummary is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interval) || (has(self.initProvider) && has(self.initProvider.interval))",message="spec.forProvider.interval is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.notificationTargetId) || (has(self.initProvider) && has(self.initProvider.notificationTargetId))",message="spec.forProvider.notificationTargetId is a required parameter"
	Spec   HeartbeatSpec   `json:"spec"`
	Status HeartbeatStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HeartbeatList contains a list of Heartbeats
type HeartbeatList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Heartbeat `json:"items"`
}

// Repository type metadata.
var (
	Heartbeat_Kind             = "Heartbeat"
	Heartbeat_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Heartbeat_Kind}.String()
	Heartbeat_KindAPIVersion   = Heartbeat_Kind + "." + CRDGroupVersion.String()
	Heartbeat_GroupVersionKind = CRDGroupVersion.WithKind(Heartbeat_Kind)
)

func init() {
	SchemeBuilder.Register(&Heartbeat{}, &HeartbeatList{})
}
